### ISSUE TITLE
Add Sn prefix to project names in all places

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#1001]
Follow-up of #958 and a sibling issue to https://github.com/foundry-rs/starknet-foundry/issues/998

Our project binaries use `sn` prefixes in all places, but usages of names with and without prefixes in other places are inconsistent. 

E.g. https://github.com/foundry-rs/starknet-foundry/blob/e0bdc7ce715bb2112380c7be8ddc6503e45ee494/crates/cast/src/main.rs#L21
or in docs headings

We should consider if we want to use consistent names in all places.

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
I am a web3 developer

### How I plan on tackling this issue
I will add `sn` prefixes in all places that it need to be added

**Comment by PedroRosalba** [comment]
Is this issue still available?

**Comment by Aditya-040** [comment]
I’d like to help with this.
