### ISSUE TITLE
Add `Scarb.toml` forge reference

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#1017]
Add Scarb.toml forge tool reference to documentation. It should show all possible configuration keys and values for forge with explanations.

Also generate the template with commented out parts, similar to `tsconfig.json`.

**Comment by MaksymilianDemitraszek** [comment]
I think it would be nice to also/instead include commented out options in the `Scarb.toml` in the `tsconfig.json` to improve the discoverability.
