### ISSUE TITLE
[Tracking issue] Extensive test set verifing if cheatable starknet behaviour is consisten with starknet behaviour

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#104]
Things to consider: 

- [x] #237
- [ ] nonces
- [ ] block numbers

**Comment by cptartur** [comment]
Feel free to create separate issues from each of the checkbox

**Comment by cptartur** [comment]
Taking all of these, will publish draft sometime later
