### ISSUE TITLE
Increase max-fee in deploy account docs

### ISSUE THREAD

**Issue by drknzz** [foundry-rs/starknet-foundry#1078]
### Which component is your feature related to?

Cast

### Feature Request

There is `--max-fee 864600000000` specified in docs when deploying an account, but sending a tx with such results in
```
error: Max fee is smaller than the minimal transaction cost (validation plus fee transfer)
```

[Here](https://foundry-rs.github.io/starknet-foundry/starknet/account.html?highlight=864600000000#general-example) and probably in some other places.

**Comment by Vap0RSh4wN** [comment]
hi, may I ask how can I solve this problem? o(╥﹏╥)o
thanks!

**Comment by THenry14** [comment]
> hi, may I ask how can I solve this problem? o(╥﹏╥)o thanks!

Hi, this issue is aliready assigned, sorry
