### ISSUE TITLE
Write design document on `setup`s

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#1115]
It should be inspired by this: https://docs.swmansion.com/protostar/docs/legacy/testing#setup-hooks

A some kind of function or similar that is executed before running tests that setups the state. It should be cached or stored otherwise and not re-executed between test runs.

**Comment by MaksymilianDemitraszek** [comment]
IMO this should not be included in TODO rn, seems for me like a far future idea
