### ISSUE TITLE
Extract `build_readable_text` into separate crate

### ISSUE THREAD

**Issue by abulenok** [foundry-rs/starknet-foundry#1127]
.. so we can reuse it in deployment scripts
https://github.com/foundry-rs/starknet-foundry/pull/1067#discussion_r1392818816

**Comment by THenry14** [comment]
potentially this as well https://github.com/foundry-rs/starknet-foundry/pull/1067/files#r1392808607

**Comment by THenry14** [comment]
> Is this still relevant?

yup, it's still only 3 weeks old

**Comment by Arcticae** [comment]
FYI this might not be needed because of new printing macros and `Display` trait

**Comment by THenry14** [comment]
from #1692 

> https://github.com/foundry-rs/starknet-foundry/issues/1692#issuecomment-1941220124
