### ISSUE TITLE
Improve error reporting in `CairoHintProcessor` logic in deployment scripts

### ISSUE THREAD

**Issue by abulenok** [foundry-rs/starknet-foundry#1168]
in `execute_cheatcode_hint` and `match_cheatcode_by_selector` we either return `HintError` or do `.expect`. The first one will result in a more user-friendly message.
I suggest we return `HintError` whenever the error most probably depends on the user input and `.expect` when the error most probably comes from a bug in our code

**Comment by abulenok** [comment]
related discussion https://github.com/foundry-rs/starknet-foundry/pull/1067#discussion_r1392809630

**Comment by THenry14** [comment]
let's remove the dependency `cheatnet::cheatcodes::EnhancedHintError;` altogether, as per discussion on slack.

**Comment by abulenok** [comment]
@THenry14 seems to be not relevant anymore, since we use RuntimeExtensions now

**Comment by THenry14** [comment]
Sure, let's just close this one then :+1:
