### ISSUE TITLE
Incompatible ABIs cause the `contract_class` code parsing to crash

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1175]
### Which component is your bug related to?

Forge

### Foundry Version

0.10.2

### What operating system are you using?

MacOS

### What system architecture are you using?

x86

### What happened

We don't need the ABIs to be parsed for the code to execute, so we should consider omitting the parsing overall (or parse selectively), since the following example is crashing the newer parser (no backwards compatibility).

### Trace

Reproduction:

```
#[derive(Serde)]
struct Propdetails {
    payload: felt252,
}

#[starknet::interface]
trait IGovernance<State> {
    fn get_proposal_details(self: @State, param: felt252) -> Propdetails;
}

#[test]
#[fork(url: "https://rpc.starknet-testnet.lava.build", block_id: BlockId::Number(904597))]
fn test_forking_functionality() {
    let gov_contract_addr: ContractAddress = 0x7ba1d4836a1142c09dde23cb39b2885fe350912591461b5764454a255bdbac6.try_into().unwrap();
    let dispatcher = IGovernanceDispatcher { contract_address: gov_contract_addr };
    let propdetails = dispatcher.get_proposal_details(1);
    assert(propdetails.payload==0x78b4ccacdc1c902281f6f13d94b6d17b1f4c44ff811c01dea504d43a264f611, 'payload not match');
}

```
Error:
```
thread 'tokio-runtime-worker' panicked at crates/cheatnet/src/forking/state.rs:213:90:
called `Result::unwrap()` on an `Err` value: Error("missing field `kind`", line: 1, column: 2356)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR] task 10 panicked
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by tensojka** [comment]
Thanks for creating the issue, I can confirm that this happens on v0.10.0 and v0.10.1 too.

**Comment by Arcticae** [comment]
Blocked by #1211

**Comment by tensojka** [comment]
Attempted to build from source with code from #1363 and the issue still isn't fixed, getting the same error.

**Comment by Arcticae** [comment]
@tensojka is it the same class hash that's in the issue description?
