### ISSUE TITLE
Add validation of hash value in `BlockId::Hash` variant

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#1179]
Tagged with `TODO #1179`
We parsed the `BigInt` from db with `Felt252::from` which does sth like

```rs
value.try_into().unwrap_or_else(|_| &*CAIRO_PRIME_BIGUINT - (-value as u128)),
```

After moving test collection to Scarb, the appropriate range should be checked there, then we can pass the number as a String (see #1119)

**Comment by Arcticae** [comment]
To be verified when plugins are working

**Comment by piotmag769** [comment]
https://github.com/foundry-rs/starknet-foundry/pull/2044/files#r1654464417

Marked with TODO
