### ISSUE TITLE
Investigate preblem with fork cache

### ISSUE THREAD

**Issue by tkumor3** [foundry-rs/starknet-foundry#1188]
Which component is your bug related to?
Forge

Foundry Version

What happened

In some circumstances, tests can be run only one by one and after each run, the fork cache should be clean. Order of test execution is not important.

Code to reproduce

Error:
![Image](https://github.com/foundry-rs/starknet-foundry/assets/15279784/33977142-5857-47fe-9337-16b8fe9370b8)

**Comment by Arcticae** [comment]
This should not happen in the newer version
