### ISSUE TITLE
Update docs and `snforge init` to use dev-dependencies

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#1221]
https://github.com/software-mansion/scarb/issues/717
Scarb supports dev dependencies now (in next version)

**Comment by piotmag769** [comment]
Will be unblocked when new Scarb is released

**Comment by Arcticae** [comment]
This will make impossible to use call trace and other cheatcodes in contracts

**Comment by Arcticae** [comment]
@piotmag769 will this work without plugins?

**Comment by piotmag769** [comment]
It will

**Comment by tomek0123456789** [comment]
Closed in #1871
