### ISSUE TITLE
Better trace info

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#1236]
Currently blockifier does not include any trace info so when transaction rejects you cannot be sure which contract failed.

We could do something like this
```
match Contract.function() {
     OK(_) => {},
      Err() => print_last_error_trace()
}

```
ofc interface can be improved to be more idiomatic

**Comment by Arcticae** [comment]
We should agree on some kind of interface in here, to allow extending it with some resource usage info as well 
cc @war-in @piotmag769

**Comment by war-in** [comment]
It would be nice to have some design doc (or MVP PR) for collecting error traces and used resources. I think both should be unified since they collect trace information. Maybe cheatnet state could keep such data?

**Comment by MaksymilianDemitraszek** [comment]
I think it is not design-doc worthy, MVP PR is a better option
