### ISSUE TITLE
Use functions for buffer reading

### ISSUE THREAD

**Issue by drknzz** [foundry-rs/starknet-foundry#1272]
### Which component is your feature related to?

Forge

### Feature Request

https://github.com/foundry-rs/starknet-foundry/pull/1270/files#diff-8aa925b526143c705871a1be89c6ff1c8e46bc7dcbc453e0ce8b5a7a785bcb94R625-R642

These functions should be used in the whole file (currently they are used only in spoof)

**Comment by drknzz** [comment]
> Regarding our discussion during the meeting, this is a nice thing to do and should be done, though I would not call array of felts buffer, because there is a different structure named buffer used to write to cairo memory.

Please rename the functions adequately as a part of the issue then.

**Comment by MaksymilianDemitraszek** [comment]
Functions are fine, I mean argument name `buffer`

**Comment by piotmag769** [comment]
Wasn't it done in #1440? cc @abulenok
