### ISSUE TITLE
Add `--no-vcs` flag to `snforge init`

### ISSUE THREAD

**Issue by tkumor3** [foundry-rs/starknet-foundry#1273]
Add flag to allows creating a new snforge project without git initialization. Scarb new supported it by adding --no-vcs flag. [docs](https://docs.swmansion.com/scarb/docs/guides/creating-a-new-package.html)

**Comment by 0xkyng** [comment]
Hello, could i take this issue? It seems nobody has been assigned yet..

**Comment by Arcticae** [comment]
@0xkyng feel free to work on this one!

**Comment by 0xkyng** [comment]
Alright. Thanks
