### ISSUE TITLE
Upgrading cairo 0 contracts when testing against forks doesn't work correctly

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#1288]
https://t.me/starknet_foundry_support/1368

Info from the user:

Problem occurs when testing the OZ cairo 0 account upgrade to cairo 1 using a forked network.
It seems like the function for upgrade is being called but the class hash and the behaviour of contract doesn't change.
Everything works correctly when upgrading cairo 1 contract against a forked network.

**Comment by Arcticae** [comment]
@piotmag769 is this still relevant or can we close?
