### ISSUE TITLE
Remove any `Raw` types from forge-runner

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#1299]
forge-runner should include and know only validated versions of types. All validation should be done in `forge`

**Comment by piotmag769** [comment]
Was already done in #1157 I believe, so that can be an inspiration

**Comment by piotmag769** [comment]
@tkumor3 isn't it solved in #1333?

**Comment by Arcticae** [comment]
@piotmag769 not sure which PR was it done in but it's done on master, i've verified
