### ISSUE TITLE
Investigate dependabot bump cairo-vm

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#1318]
https://github.com/foundry-rs/starknet-foundry/pull/1264#issue-2020906516

Would be nice to be running on the same vm version as the compiler (cairo)

**Comment by cptartur** [comment]
Cairo uses version 0.8.2 for the 2.4.0 release: https://github.com/starkware-libs/cairo/blob/a4de08fbd75fa1d58c69d054d6b3d99aaf318f90/Cargo.toml#L69

Blockifier 0.8.7: https://github.com/starkware-libs/blockifier/blob/a98899cdab1d9d3af9cff4aff9737970ca5a161c/Cargo.toml#L27

We are on 0.8.7: https://github.com/foundry-rs/starknet-foundry/blob/32ee3591fba6e22c0bd1ca306d3f881fb5109904/Cargo.toml#L45

We should either do nothing (my suggestion) or downgrade. Don't see a point in bumping to 0.9.1 as per dependabot PR https://github.com/foundry-rs/starknet-foundry/pull/1264

**Comment by cptartur** [comment]
cc @Arcticae @MaksymilianDemitraszek

**Comment by Arcticae** [comment]
I'm okay with this takeaway
