### ISSUE TITLE
sncast Invalid transaction nonce

### ISSUE THREAD

**Issue by milancermak** [foundry-rs/starknet-foundry#1336]
### Which component is your bug related to?

Cast

### Foundry Version

0.12.0

### What operating system are you using?

MacOS

### What system architecture are you using?

arm

### What happened

I used `sncast declare` to declare a contract. Then I did some transactions with the same account.

After a while, I wanted to `sncast declare` again, but the operation failed with `error: Invalid transaction nonce`. I had to check the nonce of the last TX my account did and then pass a `--nonce` arg with the next nonce to the declare command. It then succeeded.

IMO nonce checking should be built in to enable a flow like described above.

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by THenry14** [comment]
Hi @milancermak , thanks for opening an issue! We depend on an sdk to fetch the nonce each time we try to send a transaction, but perhaps there are some issues. I will try to figure out what is wrong, and maybe explicitly fetch the nonce on sncast end to avoid this issue. Will let you know when something's ready. Thanks, and sorry for inconvenience caused.
