### ISSUE TITLE
Share extension logic between forge & cast 

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#1340]
Currently IO runtime is coupled with cheatnet stuff. 
We should move all io related functions to runtime extension and then move the extension to runtime crate so cast can reuse it.

**Comment by piotmag769** [comment]
Is this still relevant considering we may want to consolidate print implementations with corelib? If corelib print works within contracts we can just remove IORuntime alltogether

**Comment by MaksymilianDemitraszek** [comment]
@piotmag769 You mix runtime level logic and language. We will consilidate it on the language layer, I am not sure about the runtime layer

**Comment by piotmag769** [comment]
I guess we can do that, but the only reason for IORuntime existing is print in contracts, otherwise it can be rewritten to just include common/default cheatcode impls in general, wdyt?

**Comment by piotmag769** [comment]
Nvm, missunderstood the idea of this task
