### ISSUE TITLE
Declaring duplicate class with `sncast` returns `error: Internal error`

### ISSUE THREAD

**Issue by parketh** [foundry-rs/starknet-foundry#1343]
### Which component is your bug related to?

Cast

### Foundry Version

0.12.0

### What operating system are you using?

MacOS

### What system architecture are you using?

arm

### What happened

Declaring an existing (duplicate) contract class with `sncast` returns an uninformative error.

```
command: declare
error: Internal error
```

In previous versions a descriptive error was thrown. The issue may be caused by a change to the RPC spec rather than Foundry itself, however I haven't investigated further at this stage.

### Is there an existing issue for this?

- [x] I have searched the existing issues and verified no issue exits for this problem.

**Comment by THenry14** [comment]
Hi @parketh , thanks for opening an issue! This is connected with rpc spec and sdk we are using. I will try to mitigate this problem by defining our own error messages based on status code returned by node. Will let you know when it's ready, thanks.

**Comment by THenry14** [comment]
Hi again! I have added a few error mappings to cast, which should greatly improve the error messages. Most errors should be already covered (and the change was released in latest release 0.13.1), and we'll try to work closer with sdk and node implementators to make sure those errors are standardized and more descriptive from now on. Thanks again for opening this issue.
