### ISSUE TITLE
Research reimplementing panic-data parsing without the regexps

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1344]
Panic data now is parsed from string based on the textual representation of felts, 
we should research it while trying to implement #1236 since it might require lowering the abstraction level we operate on.

Related code:
https://github.com/foundry-rs/starknet-foundry/blob/03bbebdc6abd70db2a0ecb1acbd9b00ab7aded4a/crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/panic_data.rs#L5

**Comment by piotmag769** [comment]
I don't see how it is related to #1236 and how to do it in a reasonable way tbh

**Comment by piotmag769** [comment]
This is not doable so we can close it I guess, right?

**Comment by Arcticae** [comment]
I will keep it open in case it's doable in the future.
