### ISSUE TITLE
Use `append_span` in snforge_std

### ISSUE THREAD

**Issue by drknzz** [foundry-rs/starknet-foundry#1379]
### Which component is your feature related to?

Forge

### Feature Request

👍

**Comment by TAdev0** [comment]
@drknzz  hello , is this refactoring still needed? I can work on it in the next days.

**Comment by drknzz** [comment]
> @drknzz  hello , is this refactoring still needed? I can work on it in the next days.

Hey, I think it's still up for doing. Feel free to open a PR if you're interested 👍
