### ISSUE TITLE
Make forge stop parse sierra types directly

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1394]
We should check that we have all the info needed from the scarb compilation (return types, params are required from sierra in our runner).

Volatility of the types across sierra versions that we use (parameter types, panic type etc.) should be addressed in this issue

**Comment by piotmag769** [comment]
Don't we already use sierra?

**Comment by Arcticae** [comment]
yeah i think we do 
@cptartur did you start working on it?

**Comment by piotmag769** [comment]
@Arcticae I meant that since scarb outputs sierra to us all info we need are already there, we could collect this info on our side instead
