### ISSUE TITLE
Import a library ([starknet::component]) inside another library ([starknet::component]) 

### ISSUE THREAD

**Issue by rajeebkm** [foundry-rs/starknet-foundry#1403]
### Which component is your feature related to?

Forge

### Feature Request

<img width="583" alt="Screenshot 2023-12-16 at 21 21 49" src="https://github.com/foundry-rs/starknet-foundry/assets/97892873/faafb181-9aa9-4dee-a60e-b389e1554547">

Trying to import ```LibAsset component``` in ```LibFees``` component, and getting this warning error. Please look into it.

**Comment by Cevedale** [comment]
Take a look at the file paths for both the 'LibAsset' and 'LibFees', check the export, it should look like that: 
export { LibAsset };
When you try to import the 'LibAsset' , check the statement:
import { LibAsset } from 'path/to/LibAsset';
Your module resolution configuration should be set up correctly. For example, in a TypeScript project, check the tsconfig.json file for proper configuration.
Let me know if you found it useful

**Comment by Arcticae** [comment]
This seems like an issue related to either vscode extension, or a wrong cairo version, so either way unrelated to forge.
Please submit an issue in [the cairo repo](https://github.com/starkware-libs/cairo) instead
Closing
