### ISSUE TITLE
feat: assert_not_emitted

### ISSUE THREAD

**Issue by milancermak** [foundry-rs/starknet-foundry#1409]
### Which component is your feature related to?

Forge

### Feature Request

There are cases where I want to assert an event was *not* emitted. It would be great if Foundry would have built in support for this check.

If you deem it as a valid feature, I can submit a PR for it as well.

**Comment by Arcticae** [comment]
Hey @milancermak!
Feel free to work on this one, shouldn't be too difficult to implement in `snforge_std` :)
