### ISSUE TITLE
Enforce `fuzzer_runs >= 1` everywhere

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#1435]
It is checked in `RunParams::from` with `assert!` but only enforced when passing `--fuzzer_runs` to the cli. It should be enforced in config from Scarb.toml (`validate_raw_work_config`) and in the test-collector in `forge_try_extract_test_config`.

The best solution would be to somehow constraint the type of `fuzzer_runs` to have a domain of `u32` integers that are `>= 1`, but idk if that's doable in Rust

**Comment by Arcticae** [comment]
Requires changing implementation of fuzzer in `snforge` as well.
