### ISSUE TITLE
Make sure gas calculations are aligned with starknet `>=0.13.0`

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#1445]
New docs: https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/fee-mechanism/#gas_cost_per_cairo_step_or_builtin_step

**Comment by war-in** [comment]
I think everything should be fine because we use the blockifiers' function to calculate the gas. @piotmag769 could you verify it too?

**Comment by piotmag769** [comment]
@war-in We for sure have this place outdated https://github.com/foundry-rs/starknet-foundry/blob/f0275a9ae0ebd3e9f850f92c2e7a1d8601557d6e/crates/runtime/src/starknet/context.rs#L44

https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/fee-mechanism/#gas_cost_per_cairo_step_or_builtin_step
