### ISSUE TITLE
Parsing arguments from memory panics

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1469]
We should instead fail the test and suggest upgrading the tool/using higher specific version

This was the case especially for the new Cheatcode interface which can be used as a case study

**Comment by MaksymilianDemitraszek** [comment]
I think we shouldn't suggest using any specific version when parsing arguments. User might use cheatcode API directly as well, we should just handle it nicely. Version incompatibility will be resolved with #1481

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek could you elaborate on what needs to be done exactly?

**Comment by MaksymilianDemitraszek** [comment]
We shouldn't rust level panic when we cannot parse cheatcode input
