### ISSUE TITLE
Implement fetching env variables in snfoundry

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#1475]
There should be a possibility to get env variables from the env. They should be obtainable from Scarb.toml's `tools.xyz` like so: "env=$my_env".

**Comment by Arcticae** [comment]
Solution for #1690

**Comment by piotmag769** [comment]
This is actually what we thought #1690 is relating to, #1690 is about our CI xD

cc @Arcticae @MaksymilianDemitraszek

**Comment by MaksymilianDemitraszek** [comment]
Foundry should be able to resolve environmental variables from both Scarb.toml and snfoundry.toml. It means that
a value field="$ENVVAR", is read from scarb config and snfoundry.toml as a string "$ENVVAR". Later foundry should resolve all environmental variables to its values by reading and replacing them.
