### ISSUE TITLE
Flexible printing

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#1482]
We should provide a flexible printing mechanism which simplifies printing more complex structures from cairo (you can implement a print for specific data type in rust).

This problem arises in printing traces as well as in deployment script logging.

If print is not implemented for a specific  structure we should lean back to default print.

**Comment by MaksymilianDemitraszek** [comment]
IMO this is reasonably important as we need this in cast cc @THenry14

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek this seems not relevant since `Display` trait will be introduced

**Comment by Arcticae** [comment]
Related: #1493
