### ISSUE TITLE
Non-deterministic missing contracts in forking

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1497]
At times there are some false-positives when trying to retrieve/interact with contracts, namely:
```
Got an exception while executing a hint: Hint Error: Requested contract address ContractAddress(PatriciaKey(StarkFelt("0x00000005dd3d2f4429af886cd1a3b08289dbcea99a294197e9eb43b0e0325b4b"))) is not deployed.
```
(mainnet)

Hint: might be related to a caching issue

**Comment by enitrat** [comment]
Another error that might be related:

```
[FAIL] unruggable::tests::fork_tests::test_ekubo::test_ekubo_launch_meme_with_pool_1percent

Failure data:Failed to read from state: Unable to get block with tx hashes from fork, err: StarknetError(StarknetErrorWithMessage { code: Known(BlockNotFound), message: "Block not found" }).
[FAIL] unruggable::tests::fork_tests::test_ekubo::test_ekubo_launch_meme

Failure data:Failed to read from state: Unable to get block with tx hashes from fork, err: StarknetError(StarknetErrorWithMessage { code: Known(BlockNotFound), message: "Block not found" }).
[PASS] unruggable::tests::fork_tests::test_ekubo::test_ekubo_launch_meme_token1_price_below_1, gas: ~1762.88
Number of the block used for fork testing = 495876
```

Some fork tests pass, some other have a "Block not found" error

**Comment by enitrat** [comment]
Over the last 10 tests 8 of them have failed because of issues due to the forking feature. When running two very similar tests, forking the same block of the same network and calling the same contracts, one of the succeeds and one of them fails with `Contract not deployed`

**Comment by Arcticae** [comment]
@enitrat have you been experiencing it since? 
I have not been able to reproduce this unfortunately, perhaps there is a problem with specific kinds of contracts , could you share the address?
Also, what node provider are you using? (so that i could perhaps test that possibility out) (or is it self-hosted node?)

**Comment by enitrat** [comment]
You can probably try multiple runs of  these tests with the Blocktag.Latest. I was using nethermind-rpc, but since it was working fine for some tests and not for others I guess this must be a problem of caching (unless the same requests are duplicated multiple times and not cached?)

https://github.com/keep-starknet-strange/unruggable.meme/pull/147
