### ISSUE TITLE
Implement docs tests in cairo from mdbook for forge

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1533]
### Which components does the task require to be changed?

snforge

### Description

Cairo book has this implemented and we can verify if their architecture is usable with our tests. If so, we can implement it, if not, let's design a custom solution (if this get's too complex, a design doc may be necessary).

**Comment by piotmag769** [comment]
Maybe we can reuse this
https://github.com/cairo-book/cairo-book/tree/main?tab=readme-ov-file#work-locally-cairo-programs-verification
https://rust-lang.github.io/mdBook/format/mdbook.html#including-files
