### ISSUE TITLE
Unify way of handling gas calculation with traces

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1535]
### Which components does the task require to be changed?

snforge

### Description

We should unify how we handle has calculation all across the board, so that the result we output are directly correlated (summed up) to the trace fragments with associated costs.

**Comment by piotmag769** [comment]
Blocked by #1541

**Comment by war-in** [comment]
blocked by #1752

**Comment by Arcticae** [comment]
@piotmag769 feel free to reopen if it's relevant, but it doesn't seem to be anymore
