### ISSUE TITLE
Update `should_panic` expected failures docs

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#1536]
### Which components does the task require to be changed?

snforge

### Description
We don't have all possible options listed here
https://foundry-rs.github.io/starknet-foundry/testing/testing.html#expected-failures

Different formats are supported, listed here:
https://github.com/starkware-libs/cairo/blob/c1f9ed85f3e94452819f2436358ee3a97d896949/crates/cairo-lang-test-plugin/src/test_config.rs#L91

**Comment by Arcticae** [comment]
@piotmag769 please describe the issue more comprehensively
