### ISSUE TITLE
Make `CallEntryPoint` from blockifier derive `Serialize` and `Deserialize`

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#1554]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

So we can remove `crates/cheatnet/src/blockifier_structs.rs`, see #1549

**Comment by MaksymilianDemitraszek** [comment]
We don't need to do so. Profiler will expose those strucutres as a package to simplfy meeting a contract. Relying on blockifier format in such communication protocol (which cannot have any breaking changes) is a bad idea.
