### ISSUE TITLE
Re-integrate USC binary

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1563]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

Blocked by api changes in https://github.com/software-mansion/universal-sierra-compiler/issues/17

This should include re-revert of #1562, and if this task is being done after we migrate to cairo with [this commit](https://github.com/starkware-libs/cairo/commit/4223fd0668d2cf7049c41b90fb55f36dc2f5c3de), also an integration in the test compilation.

**Comment by drknzz** [comment]
Compilation step introduced in #1626:

https://github.com/foundry-rs/starknet-foundry/blob/a4bf9d3b42eba3699c3e412379c5864eb2f2b601/crates/forge-runner/src/lib.rs#L198
