### ISSUE TITLE
Add --manifest-path option to `snforge`/`sncast`

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1568]
### Which components does the task require to be changed? (think hard pls)

snforge, sncast

### Description

In order to facilitate running snforge/sncast from other directory than current

**Comment by piotmag769** [comment]
Didn't we explicitly decide to ditch this idea? cc @THenry14 @MaksymilianDemitraszek 
Btw you can do that already via `SCARB_MANIFEST_PATH` env var

**Comment by THenry14** [comment]
Yup, We already started moving towards removing this flag from sncast as per https://github.com/foundry-rs/starknet-foundry/pull/1485

**Comment by MaksymilianDemitraszek** [comment]
Should we close this one then?

**Comment by Arcticae** [comment]
@piotmag769 i cannot find this in the docs, is it undocumented?

**Comment by Arcticae** [comment]
BTW Why did we decide to ditch that, isn't that what other (sometimes respected) tools do?

**Comment by MaksymilianDemitraszek** [comment]
I am not sure if the scarb env is not enough.

**Comment by piotmag769** [comment]
@Arcticae it is in the design doc introduced in #1485. I agree with Maks that the env var is sufficient
