### ISSUE TITLE
Bytecode replacement cheatcode

### ISSUE THREAD

**Issue by marcellobardus** [foundry-rs/starknet-foundry#1578]
### Which component is your feature related to?

Forge

### Feature Request

Equivalent of https://book.getfoundry.sh/cheatcodes/etch?highlight=etch#etch

**Comment by marcellobardus** [comment]
Yes, I am wondering if it is possible to mimic this behaviour without implementing a replacement logic on the contract level.
So normally when a contract is called and a storage slot that is access is empty it would revert.
We want to fork the network, replace the bytecode and make it emit an event instead.
However we want to avoid a setup where we include the "switch" logic as part of the contract deployed onchain.

**Comment by Arcticae** [comment]
@marcellobardus I think this one is valid, since now it's not doable. Thanks for the context - we will try to resolve this as soon as possible
