### ISSUE TITLE
Record logs equivalent

### ISSUE THREAD

**Issue by marcellobardus** [foundry-rs/starknet-foundry#1579]
### Which component is your feature related to?

Forge

### Feature Request

Equivalent of https://book.getfoundry.sh/cheatcodes/record-logs?highlight=recordLogs#recordlogs

**Comment by Arcticae** [comment]
@marcellobardus isn't that covered by the `spy_events` ?
https://foundry-rs.github.io/starknet-foundry/appendix/cheatcodes/spy_events.html

**Comment by marcellobardus** [comment]
It is thanks for pointing this!
