### ISSUE TITLE
sncast declare report "Failed to find artifacts in starknet_artifacts.json file"

### ISSUE THREAD

**Issue by zouyuxuan** [foundry-rs/starknet-foundry#1582]
### Which component is your bug related to?

sncast

### Foundry Version

0.14.0

### What operating system are you using?

MacOS

### What system architecture are you using?

arm

### What happened

i use sncast declare contract report "Failed to find artifacts in starknet_artifacts.json file. Please ensure you have enabled sierra and casm code generation in Scarb.toml",but my Scarb.toml has set sierra = true,casm = true,this is my Scarb.toml file ,
and scarb:2.5.0 ,cairo: 2.5.0 ,sierra: 1.4.0

[package]
name = "my_contract"
version = "0.1.0"
edition = "2023_10"

[dependencies]
starknet = "2.4.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.14.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[tool.sncast.account3]
account = "account3"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

**Comment by THenry14** [comment]
I believe this issue was also raised on tg support channel. It turned out user had passed improper contract name to `--contract-name` flag - supplying scarb package name instead of contract name to it.
