### ISSUE TITLE
Use structs for inputs/outputs

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#1625]
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

For all our subcommands, we should start using structs for inputs and outputs to declutter args lists and return types. Most (if not all) functions should already be using structs for outputs, but no all of them use them for inputs (eg account/create vs account/add). 

The goal of this task is to refactor our subcommands (and other function, if it makes sense) to use structs.

**Comment by Arcticae** [comment]
Closing in favour of #276
