### ISSUE TITLE
Count syscalls properly

### ISSUE THREAD

**Issue by drknzz** [foundry-rs/starknet-foundry#1631]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

Syscalls like Deploy / CallContract are currently not counted properly due to when deploying / calling contract through cheatcode / dispatcher.

They probably should be manually incremented here:
https://github.com/foundry-rs/starknet-foundry/blob/2f3775b273936616cea3c5ad842adc4749b120fa/crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/mod.rs#L145

---

Reference:
https://github.com/foundry-rs/starknet-foundry/blob/85728f429b0a91e79519b16ad153ccdc2dd4ddf1/crates/forge/tests/data/erc20_package/tests/test_complex.cairo#L30

**Comment by piotmag769** [comment]
Make sure to properly add appropriate syscalls for store/load too.
We should make sure there are no more places where syscalls can be executed without omitting `CheatableSyscallRuntime` and if they are increment syscalls counter in those places as well
