### ISSUE TITLE
Implement `.env` based fetching of node URL for snfoundry CI

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1690]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

It should be stored locally in .env file and on CI in secrets

We need to make sure that it's also accessible to forking repos, when we approve the run ourselves

**Comment by THenry14** [comment]
cargo configs could potentially be used for this (instead of env files) as well https://doc.rust-lang.org/cargo/reference/config.html

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek please describe the proposed solution here

**Comment by MaksymilianDemitraszek** [comment]
Foundry should be able to resolve environmental variables from both `Scarb.toml` and `snfoundry.toml`. It means that
a value `field="$ENVVAR"`, is read from scarb config and `snfoundry.toml` as a string `"$ENVVAR"`. Later foundry should resolve all environmental variables to its values by reading and replacing them.

**Comment by tomek0123456789** [comment]
Closed in #2003, #2004 and #2006
