### ISSUE TITLE
Scarb artifact name change

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#17]
In new scarb version the artifact name will change. Right now it is:

[package name].starknet_artifacts.json

and it will change to

[target name].starknet_artifacts.json

In most cases target name is the same as package name, but it could be different. We should take a target name from scarb metadata, and use the information to search for starknet_artifacts.json file
https://github.com/foundry-rs/starknet-foundry/blob/c04585092890f3cd351b36b411a4dae651c35feb/crates/cast/src/starknet_commands/declare.rs#L109

Docs for scarb metadata can be found here:
https://docs.rs/scarb-metadata/latest/scarb_metadata/struct.TargetMetadata.html#structfield.name

An example on how we retrieve some metadata can be found here:
https://github.com/foundry-rs/starknet-foundry/blob/c04585092890f3cd351b36b411a4dae651c35feb/crates/cast/src/starknet_commands/declare.rs#L91

**Comment by bartekryba** [comment]
Wasn't it resolved in #188?

**Comment by THenry14** [comment]
@bartekryba issue you linked looks like a PR for forge, this issue is for cast

**Comment by THenry14** [comment]
@cptartur Not sure about it, my understanding was that the change is pretty straightforward, but perhaps I'm wrong. Isn't it just about getting metadata from scarb, getting all targets and then trying to figure out which one of them should be used? (we have an information about contract name so perhaps it is enough)

**Comment by cptartur** [comment]
I've looked at #188 again and it looks simple enough
