### ISSUE TITLE
MVP function level profiling

### ISSUE THREAD

**Issue by war-in** [foundry-rs/starknet-foundry#1725]
### Which component is your feature related to?

Forge

### Feature Request

@MaksymilianDemitraszek please elaborate on that 🙏

**Comment by piotmag769** [comment]
Blocked by #846

**Comment by MaksymilianDemitraszek** [comment]
We want the graph to be a call graph of all functions not only entry-points.

Relevant mappins are already built in the cairo compiler. We need to extend scarb to be able to produce artifacts from those which profiler will be able to consume as optional.
