### ISSUE TITLE
*build_contracts.sh* doesn't recompile contracts

### ISSUE THREAD

**Issue by drknzz** [foundry-rs/starknet-foundry#1732]
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

When built locally, the contracts are not recompiled after scarb version changes, resulting in out-of-date class hashes and addresses used in tests.

https://github.com/foundry-rs/starknet-foundry/blob/9a1b4bc0c85c99f2ec21eb62c0ec99b8ea310e54/crates/sncast/tests/utils/build_contracts.sh#L19C5-L19C42

**Comment by THenry14** [comment]
This is by design, as they are cashed. We will remove this script altogether soon https://github.com/foundry-rs/starknet-foundry/issues/1800
