### ISSUE TITLE
Validate account address when doing `account add`

### ISSUE THREAD

**Issue by abulenok** [foundry-rs/starknet-foundry#1780]
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

https://github.com/foundry-rs/starknet-foundry/pull/1774#discussion_r1504424604

Best to change the API of this function to be usable in `account add`:
https://github.com/foundry-rs/starknet-foundry/blob/master/crates/sncast/src/lib.rs#L231-L242

**Comment by cptartur** [comment]
Duplicating #2218
