### ISSUE TITLE
Add contribution to the book

### ISSUE THREAD

**Issue by quentin-abei** [foundry-rs/starknet-foundry#1788]
### Which component is your feature related to?

Other (Please describe below)

### Feature Request

Please can you add a tutorial for contributing to the book to the readme? Or isn't that possible?

**Comment by drknzz** [comment]
Hey @quentin-abei,
I don't think we're going to have any tutorial on that.
If you wish to contribute, you can reach out for example through our [Telegram group](https://t.me/starknet_foundry) and we'll talk it through.

The main directory of the book:
https://github.com/foundry-rs/starknet-foundry/tree/master/docs/src

The file structure is the same as in the book

As for the technical side of contributing, if that's what you're asking about - we're using mdbook, about which you can read [here](https://rust-lang.github.io/mdBook/index.html).

**Comment by quentin-abei** [comment]
Hello @drknzz , I will reach out to tg and check the mdbook. Thanks for replying.
You can close this as completed.
