### ISSUE TITLE
Handle OS errors gracefully

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#1795]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

We often panic when writing/reading a file/creating dir/other OS related operation fail. We should bubble those errors instead (they will be pretty printed in main)

**Comment by Arcticae** [comment]
@piotmag769 please list the places that it's relevant in, or close the task

**Comment by piotmag769** [comment]
E.g. in this function https://github.com/foundry-rs/starknet-foundry/blob/bea25e2c5a8987992f3a7c41fe5480066c1a8e63/crates/forge-runner/src/build_trace_data.rs#L194 or this https://github.com/foundry-rs/starknet-foundry/blob/bea25e2c5a8987992f3a7c41fe5480066c1a8e63/crates/cheatnet/src/forking/cache.rs#L288

Don't have capacity to go through the whole codebase
