### ISSUE TITLE
Allow to pass array to constructor calldata

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#1804]
We should explore a possibility to support passing an array to constructor calldata, to avoid a confusion from users point of view on how to actually achieve this.

**Comment by ktarun1419** [comment]
Hello, @THenry14, may I take on this issue?

**Comment by THenry14** [comment]
Hi @ktarun1419 , sure - assigned :+1:

**Comment by ktarun1419** [comment]
Hi @THenry14  Thank you for assigning this issue to me , 
Can you please explain more about the issue?

**Comment by THenry14** [comment]
> Hi @THenry14 Thank you for assigning this issue to me , Can you please explain more about the issue?

Hi, at the moment when someone tries to (for example) invoke a contract's function that takes an array as one of its arguments (calldata), one needs to pass an array length first, and then the values. 

So for example, an array `[0x1 0x2]` needs to be passed like so: `--calldata 2 0x1 0x2`. The aim of this task it to allow users to pass calldata as `--calldata [0x1 0x2]`, without a need to specify the array length.

**Comment by THenry14** [comment]
Hi @ktarun1419 !
Hope everything's going well! Just wanted to touch base regarding this issue. If you need any input, run into questions, or would like to discuss anything, feel free to reach out. We're here to support you if you run on any blockers :) cheers!

**Comment by Arcticae** [comment]
Closing in favor of #276
