### ISSUE TITLE
Remove rpc section from docs

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#1806]
To be consulted with snforge team, but I beliebe this https://foundry-rs.github.io/starknet-foundry/development/rpc-version.html was added to docs by mistake

**Comment by THenry14** [comment]
Hi @vibenedict , sure - assigned

**Comment by THenry14** [comment]
Hi @vibenedict !
Hope everything's going well! Just wanted to touch base regarding this issue. If you need any input, run into questions, or would like to discuss anything, feel free to reach out. We're here to support you if you run on any blockers :) cheers!

**Comment by vibenedict** [comment]
Hi @THenry14, I just created the PR for this issue.
