### ISSUE TITLE
Remove goerli

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#1811]
Goerli will be removed on 11th April. We should work towards removing tests etc depending on it.

**Comment by vibenedict** [comment]
Hi, can you throw more light on the context so i can consider working on it.

**Comment by THenry14** [comment]
Hi @vibenedict , this one should be done in two parts - first is to make devnet to introduce itself as sepolia instead of goerli, and make sure all tests work (some files, like accounts file will have to be updated with sepolia prefunded accounts, goerli ones should be deleted). Second is to go through the code and remove/change all references to goerli (eg `script init` uses a contract deployed to goerli testnet, docs should be updated etc)

**Comment by ddoktorski** [comment]
As part of this task, let's also update the default `OZ_CLASS_HASH` to a newer version that supports V3 transactions. This updated version should be deployed to both Mainnet and Sepolia. One option is [0x061dac032f228abef9c6626f995015233097ae253a7f72d68552db02f2971b8f](https://starkscan.co/class/0x061dac032f228abef9c6626f995015233097ae253a7f72d68552db02f2971b8f) from the [OpenZepellin documentation](https://docs.openzeppelin.com/contracts-cairo/0.8.1/presets).
