### ISSUE TITLE
Document how are contracts compiled & collected

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1824]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

We should describe scarb <-> forge integration more thoroughly, and specifically some information about the artifacts collection

**Comment by Arcticae** [comment]
@piotmag769 if you have anything that you want to add, feel free

**Comment by piotmag769** [comment]
We can add info about declaring external (from dependencies) contracts in tests

**Comment by MaksymilianDemitraszek** [comment]
Probably this could be a design doc

**Comment by piotmag769** [comment]
@MaksymilianDemitraszek design doc for docs?

**Comment by Arcticae** [comment]
Users need to be able to access this and i don't see a reason not to put this inside of a guide of sorts

**Comment by MaksymilianDemitraszek** [comment]
Ah ok, I thought you want a dev docs not user docs, makes sense!
