### ISSUE TITLE
Add and integrate an action for USC for `setup-snfoundry`

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1858]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

Please try using composite actions in order to achieve that

When closing - please unblock https://github.com/foundry-rs/starknet-foundry/issues/1834

**Comment by piotmag769** [comment]
You can use composite actions to integrate the setup-USC action with setup-foundry action https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
