### ISSUE TITLE
Break down `spoof` into separate cheatcodes

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1885]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

So we don't leak the starknet syscall implementation and mocking particular info is more discoverable
We should consider a mechanism so that it's easier to test this, because the code will be fairly repeatable
It should be also done like this, so it's more consistent with other cheatcodes

**Comment by MaksymilianDemitraszek** [comment]
Closing, this does not make sense as an issue from the implementation perspective
