### ISSUE TITLE
Change `--add-profile` to `--update-profile`

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#1914]
Currently this flag is only concerned about the account field. It wil work if profile already exists. We should simplify its logic and instead just create or update (override) the specified profile. We should also rename the flag to `--update-profile` to better represent the logic.

**Comment by raizo07** [comment]
Hello, can this be assigned to me if it is still open?

**Comment by raizo07** [comment]
@MaksymilianDemitraszek can I DM you on Telegram maybe to get some clarifications on the task? Thank you

**Comment by MaksymilianDemitraszek** [comment]
@raizo07 please ask on the dedicated telegram group mentioned in the readme.
