### ISSUE TITLE
Change `File` struct to a type alias

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1949]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

We don't need the struct for anything and it's a simple wrapper over bytearray right now.

**Comment by princeibs** [comment]
Hi @Arcticae, I would like to fix this

**Comment by Draggu** [comment]
@princeibs feel free to open PR for this

**Comment by Arcticae** [comment]
# **Not removing wrappers on ContractClass/File structs**
## Rationale
Initially, we wanted to remove the structs as mentioned in these issues:
https://github.com/foundry-rs/starknet-foundry/issues/1945
https://github.com/foundry-rs/starknet-foundry/issues/1949
In essence, they don't bring anything special at this moment, apart from that you have to import them, construct them, and call methods of the trait implemented on them (which also needs to be imported).

## Technical overview:
In fact, we don't want to remove this, because:

- in the future we may need to implement something extra on the struct (an external trait type Into - and we can't do this in such case)
we add additional context through the struct, and ByteArray/ClassHash can be confusing when used with these traits (its significance is not clearly defined in a given context)

## User perspective:
Nothing changes

## Implementation plan:
Related issues to be closed.
