### ISSUE TITLE
Smoke tests on release

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#198]
Integrate it into new automated workflow introduced in #859 

After building binaries we should try to create new forge project with snforge and see if tests run in it. Additionally, we should try to do some basic chain interactions with sncast.

If either of these fails, the release workflow should fail. 

We could consider still uploading artifcats to a draft even if tests fail, so they can be replicated though it's not necessary - verison built directly from master branch (or specific commit/tag if that's necessary/applicable) should match this one from the release workflow.

See scarb's release workflow for reference

**Comment by piotmag769** [comment]
Is this still relevant?
cc @MaksymilianDemitraszek @cptartur

**Comment by MaksymilianDemitraszek** [comment]
Assigning to cli team @cptartur to have a clear ownership here
