### ISSUE TITLE
Update devnet to support forking

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#1985]
Since devnet started supporting forking, we can leverage this feature in our tests. Currently we manually set up contracts used in tests by building, declaring and deploying them. WIth this change, all contracts can be directly retrieved from the Sepolia testnet and will act as if they were deployed to the local devnet. This could also be used in the future for testing other account types that are not predeployed on devnet.

**Comment by MaksymilianDemitraszek** [comment]
Could you provide some description? What is the motivation behind this?
