### ISSUE TITLE
Add getTransactionStatus

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#1986]
### Which component is your feature related to?

Cast

### Feature Request

Add getTransactionStatus to sncast and scnast script

**Comment by kateberryd** [comment]
Hi @THenry14 I'll like to work on this

**Comment by THenry14** [comment]
Hi @kateberryd , I'm afraid this one is not available for external, first-time contributors as it may be a bit too complex, sorry. Feel free to pick some other issues with "good first issue" label. thanks.
