### ISSUE TITLE
Update foundry docs in cairo book and starknet book

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#1995]
We should reach out to eni and make sure he's okay with keeping it updated

**Comment by MaksymilianDemitraszek** [comment]
https://github.com/cairo-book/cairo-book/issues/416

**Comment by FriendlyLifeguard** [comment]
Hello, I am actively working on this. I will be finished by tomorrow at the latest!

**Comment by FriendlyLifeguard** [comment]
Hello, I am actively working on this. I will be finished by tomorrow at the latest!

**Comment by MaksymilianDemitraszek** [comment]
PR https://github.com/cairo-book/cairo-book/pull/754

**Comment by cptartur** [comment]
https://github.com/cairo-book/cairo-book/pull/754 was already merged
Starknet book is no longer maintained and starknet docs are being updated in #2189
