### ISSUE TITLE
contract_address_const::<0x800000000000011000000000000000000000000000000000000000000000000> error

### ISSUE THREAD

**Issue by zpano** [foundry-rs/starknet-foundry#2002]
### Which component is your bug related to?

snforge

### Foundry Version

0.17.0

### What operating system are you using?

Macos

### What system architecture are you using?

arm

### What happened

0x800000000000011000000000000000000000000000000000000000000000000 is a valid address for starknet.

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by piotmag769** [comment]
It doesn't seem like snforge related issue, more like a compiler one. You can open an issue there - https://github.com/starkware-libs/cairo
