### ISSUE TITLE
Add forge tutorial to starknet page

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#2021]
https://www.starknet.io/en/tutorials
We could add forge video tutorial to the starknet page

**Comment by EjembiEmmanuel** [comment]
Hi @MaksymilianDemitraszek can I work on this?

**Comment by MaksymilianDemitraszek** [comment]
@EjembiEmmanuel I think this issue does not require any changes to the codebase, it is something internal, it would be better if you select a different one.
