### ISSUE TITLE
Add a "recipes" section to the docs

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2024]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

It would present full examples with some context (like contracts) and practical uses.
This way users would get some code they can copy, and we can test/maintain it easily.

This idea could be also implemented as some example simple projects inside the repo, and then referencing them in the docs, describing what they do.

**Comment by kateberryd** [comment]
Hi, @Arcticae I would love to work on this

**Comment by Arcticae** [comment]
@kateberryd please do, but first try to describe here how you'd like to approach this, and what examples would you include.
