### ISSUE TITLE
Add missing docs for attributes

### ISSUE THREAD

**Issue by Draggu** [foundry-rs/starknet-foundry#2026]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

- `available_gas` 
- etc...

**Comment by Jemiiah** [comment]
@Arcticae please can i be assigned this work?

**Comment by Arcticae** [comment]
@Jemiiah if you have any questions about execution, please do ask them here or in the PR directly
@Gift-Naomi sorry, i chose the first answering :) you can look at other issues and perhaps find something for yourself

**Comment by Jemiiah** [comment]
@Arcticae  Is there any way I can get access to the document, or can you be more clear on the description because the description is a little bit vague?

**Comment by Arcticae** [comment]
@Jemiiah we support setting `#[available_gas(123)]` attribute, like in regular cairo test runner. In the scope of the task is finding where to put this information, and inform the user in the docs (`docs` directory, we use mdbook).

**Comment by Arcticae** [comment]
@Jemiiah are you working on this one? (we don't want to block others from contributing)

**Comment by Jemiiah** [comment]
sorry you can unsubscribe me
