### ISSUE TITLE
Remove `casm` from `StarknetContractArtifactPaths`

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#2035]
We should never load it from scarb, always use the usc to simplify the logic and make the contract safer (scarb does not guarantee anything about casm)

**Comment by piotmag769** [comment]
We should just aways compile here 
https://github.com/foundry-rs/starknet-foundry/blob/6ae992c45c937a640cb8f90e38c610e75b8b7192/crates/scarb-api/src/lib.rs#L56
