### ISSUE TITLE
Rename default name for accounts file

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#2047]
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

As we're nearing towards support for more account types, we should think about changing the default name for the accounts file (currently it contains open zeppelin in the name, which might be a bit conusing at first for some people). 

We will have to make sure that the transition is as smooth as possible. We should think abot and discuss possible angles we can try to solve this one, possible options to resolve this are:

- looking at two paths at first (first look for new file, if it's not there look for the old one), and warn users to change to filename thenselves (remove this after a few versions are out and just use new file as default)
- have sncast to migrate accounts to a new file 
- just do nothing, but improve error messaging (when someone uses the default and the file is not there, add an info that the default name changed and filename should be adjusted)
- something else?

**Comment by Arcticae** [comment]
Will be addresed by UAFF format, will create appropriate issue when migration is possible or planned (or will reopen this one). 
Closing this one.
