### ISSUE TITLE
Missing contract error fails the runner

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#2096]
Currently when a non-existing contract is called through dispatcher, safe dispatcher and l1executor, runner fails completely(neither through cairo panic or through result). 

It probably requires a small design doc to finalize what should be the expected behaviour in each case. Relevant tests should be added as well. 

```
[FAIL] tests::test_case::l1_handler_contract_missing

Failure data:
    Got an exception while executing a hint: Hint Error: Contract not deployed at address: 0x00000000000000000000000000000000000000000000000005db30e271c4dc26
```

**Comment by piotmag769** [comment]
https://github.com/foundry-rs/starknet-foundry/blob/892a896908412a4196cf2f844bd94400eb795a84/crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/rpc.rs#L59
This is the function that is a subject to change
