### ISSUE TITLE
Implement `Arbitrary` trait

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2108]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

Based off the conception in the design doc for fuzzing,
we should define the interfaces first and then implement accordingly

This should be a trait, which allows the user to implement the trait on their structure to be fuzzed automatically
It should be similar in concept to the [rust's arbitrary](https://docs.rs/arbitrary/latest/arbitrary/)

**Comment by cptartur** [comment]
Will probably be resolved as part of #2051 
If not, will be reopened
