### ISSUE TITLE
Implement a derive for `SerializeToFelt252Vec`

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2109]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

For reduction of code amount and complexity

**Comment by Draggu** [comment]
`SerializeToFelt252Vec` is always implemented same way that corresponding cairo type, so it can be easily derived. Same applies for `FromReader` (there is already macro for it). We should keep them together (in `conversions` or new crate, preferably `conversions` as this allows for blanket implementation for every felt type) and probably rename to something more accurate like `CairoSerialize` / `CairoDeserialize`
