### ISSUE TITLE
`load_serde` helper

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#2112]
Currently `load` requires manually parsing the data. We could implement a helper based on `load` which assumes `serde` packing as it is the usual thing people do. 
```
fn load_serde<T, +Serde<T>, +starknet::Store<T>>(
        target: ContractAddress, storage_address: felt252
    ) -> T
```

**Comment by Arcticae** [comment]
Closing in favour of #2299
