### ISSUE TITLE
Investigate E2E `sncast` flow and check its integration with `snforge`

### ISSUE THREAD

**Issue by tomek0123456789** [foundry-rs/starknet-foundry#2205]
### Which component is your feature related to?

Cast

### Feature Request

- Do E2E `sncast` flow testing and form an opinion about its UI/UX
- Check why people don't use `sncast` after testing with `snforge`

**Comment by Arcticae** [comment]
Can we post some takeaways here and close?

**Comment by Arcticae** [comment]
@tomek0123456789

**Comment by tomek0123456789** [comment]
- inconsistent error messages and codes (e.g. a transaction may fail, but cast returns code 0)
- little discoverability for sncast with forge (solution could be #2268)
- could use some other commands like in original cast (https://book.getfoundry.sh/cast/)
  * decoding results (inverse of data transformer)
  * geting account balance
  * estimate fees call
  * gas price
  * raw rpc calls
