### ISSUE TITLE
Make using RPCs in cast CLI easier

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2212]
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

- We should allow saving the RPC URL so we don't have to use profiles for using this - we're not always in a project scope, and it seems excessive, if you only want to do a few transactions in a day. 

- We could also provide some free default options (set and forget) which would be configured in installation, if no config is detected on disk. Those can be re-configured later. 

- We should allow storing a few URLs and setting a default, which will be used if no other RPC ID was specified. This means we would have to store it in a file, in the installation directory, preserving it when migrating versions.

- RPC URLs are poorly validated, this can be addressed in this or any other issue

**Comment by Arcticae** [comment]
Marking as blocked by #2221

**Comment by cptartur** [comment]
This should be addressed by the defaults in global config #2221 

> RPC URLs are poorly validated, this can be addressed in this or any other issue

Not creating issue for now, this doesn't seem that impactful. We can create one in the future.
