### ISSUE TITLE
Revamp `account add` procedure

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2218]
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

1. We should probably name it `account import` since it imports an account
2. We should validate the provided account details
3. We should have a visual guide (with screenshots) on how to do it from (argent/braavos/oz)
4. We should have a separate section for this in the documentation (preferably "Importing accounts from wallets?")
5. We should probably also cover how to import an account to a wallet
6. We should remove RPC URL and class hash (they are probably not needed - this needs to be verified thoroughly)
7. We should support configuring global keystores and leaving them in `cast` GLOBAL configuration (same concept as #2212), to have them as first class citizen as well (this can be deprecated in the future as UAFF gains adoption, but for now keystore should have better UX)

**Comment by Arcticae** [comment]
Marking as blocked by #2221

**Comment by cptartur** [comment]
From: #2323 

Make --type optional flag in sncast account add

Which component is your feature related to?
Cast

Feature Request
We can determine the account type by class hash. If we can't find a match, we use the type set by the user.
