### ISSUE TITLE
Global `cast` configuration

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2221]
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

We should consider adding a global config (perhaps like a global `snfoundry.toml`) that would keep our configuration which is relevant not only to one project, but also in different other contexts:
- RPC URLs
- accounts
- used block explorer
- defaults for those values

This would mean that we'd deprecate usage of profiles in favour of those, while adding a flag to `declare`/`script` for explicit "scarb profile" definition (now defaults to `dev` if custom profile is not `release` or `dev`).

The behavior of this should be described in a design doc, with an example usage and case study. 

Related: #2212 #2220 #2218

**Comment by cptartur** [comment]
We should address the issue of the interaction between local configs and global config in the design document.
