### ISSUE TITLE
Propose arguments when they are missing

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2242]
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

Sometimes you can forget to write the calldata in CLI, to deploy, call or invoke
In this case we should display what arguments (and what type) you should provide, with which flag etc.

If not - at least suggest on error that calldata is the problem if we detect it in the error message (that the calldata is too long, too short). The case applies to errors of type "failed to parse argument 3", "input too long for arguments" etc..

Related to #276

**Comment by cptartur** [comment]
First let's tackle #2241 and #2201 because these will probably come in handy to implement this

**Comment by cptartur** [comment]
Addressed by data transformer
