### ISSUE TITLE
Turn off Forge parallel test collection in tests

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#226]

**Comment by cptartur** [comment]
I've tried setting the env variable https://github.com/rayon-rs/rayon/blob/master/FAQ.md#how-many-threads-will-rayon-spawn to limit number of threads locally and I still got the errors about tests taking longer than 60 seconds when running locally.

Either disabling parallel test collection doesn't introduce any speedup in tests or somehow my turning off parallelism didn't work.
