### ISSUE TITLE
`declare` return result is not usable

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2272]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

Right now declare returns a serialized class hash in the bytearray which is not really usable in the code itself (if i want to deploy i.e. and don't know if it's been declared earlier). 
It should return an enum value instead and one of the variants should be `AlreadyDeclared(ClassHash)` and carrying the actual value inside. The other variant can be a misc error.

**Comment by codyx** [comment]
Experienced the same.

As a temporary workaround I used:
```cairo
fn deploy_contract(name: core::byte_array::ByteArray) -> ContractAddress {
    let contract_class = declare(name);
    let addr = match contract_class {
        Result::Ok(class) => {
            let (contract_address, _) = class.deploy(@ArrayTrait::new()).unwrap();
            contract_address
        },
        Result::Err(err) => {
            err.print();
            // IF ALREADY DECLARED:
            let declared_class_hash = class_hash_const::<
                HARDCODED_PRE_DECLARED_CLASS_HASH_SHOWN_IN_PRINTED_ERROR_ABOVE
            >();
            let my_class = ContractClassTrait::new(declared_class_hash);
            let (contract_address, _) = my_class.deploy(@ArrayTrait::new()).unwrap();
            contract_address
        }
    };
    addr
}
```
