### ISSUE TITLE
Automatic free RPC vendor configuration 

### ISSUE THREAD

**Issue by ksew1** [foundry-rs/starknet-foundry#2315]
### Which component is your feature related to?

Cast

### Feature Request

- We should automatically configure free RPC vendor to provide out of the box experience. 

- We can use this providers: 
    * [Blast](https://blastapi.io/public-api/starknet)
    * [Nethermind](https://data.voyager.online/)
    
- As this could be implemented in many ways, please start with design-doc

**Comment by Arcticae** [comment]
Duplicate of #2212
