### ISSUE TITLE
Add output abstraction

### ISSUE THREAD

**Issue by Radinyn** [foundry-rs/starknet-foundry#233]
We should add output abstraction to allow simpler and more accurate control over the output format.

Related:
#175
#74

**Comment by cptartur** [comment]
Isn't it duplicating #175?

**Comment by MaksymilianDemitraszek** [comment]
@Radinyn can you respond or close it as a duplicate 🥺 🙏

**Comment by Radinyn** [comment]
@MaksymilianDemitraszek it was already discussed on the standup and deemed not a duplicate, I'm not sure whether it isn't though.
