### ISSUE TITLE
Develop a way to issue warnings about deprecation

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2347]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

This should be implemented (and first designed) as some kind of universal mechanism where we can put deprecation warnings for items that will be disused or moved to somewhere else

**Comment by integraledelebesgue** [comment]
Cairo compiler already has a `deprecated` attribute we can use. It emits compile-time warnings with custom notes and supports Rust-like `feature` flags system. See [`LegacyMap` example](https://github.com/starkware-libs/cairo/blob/9b603b88c2e5a98eec1bb8f323260b7765e94911/crates/cairo-lang-starknet/src/plugin/plugin_test_data/contracts/raw_output#L109C1-L112C3).
