### ISSUE TITLE
Random number generation cheatcode

### ISSUE THREAD

**Issue by gaetbout** [foundry-rs/starknet-foundry#2353]
### Which component is your feature related to?

Forge

### Feature Request

I'd like a way to generate (pseudo) random number 

Task: Introduce a new cheatcode that will generate a random felt252. Follow the current implementation of other cheatcodes.

**Comment by ScottyDavies** [comment]
Hey @gaetbout can you please assign this issue to me?

**Comment by gaetbout** [comment]
I'm not sure I can, better asking one of foundry ppl,
 @piotmag769 ?

**Comment by piotmag769** [comment]
Could you TAL @cptartur?

**Comment by TropicalDog17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry2).

### My background and how it can be leveraged
I am an experienced Rust dev and have experience working on various open sources projects. 

I've implemented a cheatcode in the foundry repo: https://github.com/foundry-rs/foundry/pull/8258

### How I plan on tackling this issue
I would read the different between the original foundry and starknet-foundry, follow the current impl of other cheatcodes and derive a way to working on this particular cheatcode.

**Comment by Oshioke-Salaki** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
I am a cairo developer with alot of contributions in the starknet ecosystem. I belive i would be a perfect fit for this issue and i would love to show case my skills in this repo if given the chance.

### How I plan on tackling this issue
I would  follow the current implementation of other cheatcodes and implement one that will be able to genarate a random felt252.

**Comment by Josh-121** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
software engineering background and looking to make first contribution on here. 

### How I plan on tackling this issue
would go through the existing cheat code implementations as mentioned and carryout the task. I'm looking to deliver few hours from being assigned as theres already an existing framework. Can I get to do this?

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Hello @gaetbout, I would love to handle this,...

### How I plan on tackling this issue
Frist, Create a new  `random.rs` file,
Then, implement random number generation function using a pseudo-random number generator (PRNG) to create a felt252 value.
Then, Implement a method like generate_random_felt252 in the CheatnetState struct.
Then, update the ForgeExtension to handle the new cheatcode
update `snforge_std`,
Fianlly, document

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

**Comment by Gerson2102** [comment]
### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other Rust projects like:

- `kakarot-rpc`
- `ef-tests`
- `Madara`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by tosoham** [comment]
Can I attempt this issue?

**Comment by manlikeHB** [comment]
Hi. I am a Cairo and Rust developer with experience contributing to other projects on OD Hack. I would like to give this issue a try.

**Comment by Benjtalkshow** [comment]
Hello @gaetbout 
Can this issue be assigned to me? It will be my first time contributing to this amazing project. I write Cairo and rust. ETA 48hrs.

**Comment by cptartur** [comment]
Hey @manlikeHB, we are reassigning the issue. Are you still interested in tackling this one?

**Comment by manlikeHB** [comment]
Hi @cptartur, Yes I am.

**Comment by cptartur** [comment]
> Hi [@cptartur](https://github.com/cptartur), Yes I am.

@manlikeHB  Great, it's already assigned to you so go ahead 🙏
