### ISSUE TITLE
Refactor snforge to Reuse Existing Sierra File Paths for cairo-profiler Input

### ISSUE THREAD

**Issue by ksew1** [foundry-rs/starknet-foundry#2355]
### Which component is your feature related to?

Forge

### Feature Request

Context: `cairo-profiler` expects paths to files with serialized `VersionedProgram` (sierra format) in its input file. Right now `snforge` saves relevant sierra programs to separate files when using `--save-trace-data` or `--build-profile` and then puts paths to these files in the input file for `cairo-profiler`. This is a leftover from using `scarb-snforge-test-collector`
 
With Scarb 2.7.0 the sierra files with compiled tests are already present on the disk in the form `cairo-profiler` expects.  we Let's make `snforge` reuse the paths to these files when building input files for `cairo-profiler`.

Relevant code:
- saving sierra program
https://github.com/foundry-rs/starknet-foundry/blob/4a1aea0f9f888c9b4774af897fc010d029d0180c/crates/forge/src/run_tests/test_target.rs#L42

- passing the path to the saved sierra program around:
https://github.com/foundry-rs/starknet-foundry/blob/4a1aea0f9f888c9b4774af897fc010d029d0180c/crates/forge-runner/src/running.rs#L85
to later use it here when generating input file for cairo-profiler
https://github.com/foundry-rs/starknet-foundry/blob/4a1aea0f9f888c9b4774af897fc010d029d0180c/crates/forge-runner/src/build_trace_data.rs#L41

Originated in: https://github.com/foundry-rs/starknet-foundry/pull/2191#discussion_r1701720675

**Comment by ScottyDavies** [comment]
@ksew1 Please can you assign this task to me?
