### ISSUE TITLE
Extend `into_proc_macro_result` with warns

### ISSUE THREAD

**Issue by ksew1** [foundry-rs/starknet-foundry#2358]
### Which component is your feature related to?

Forge

### Feature Request

Marked in code with TODO.

Change Err match arm to this in `into_proc_macro_result` and fix tests

```rust
Err(mut diagnostics) => {
    diagnostics.extend(warnings);
    ProcMacroResult::new(item).with_diagnostics(diagnostics)
}
```

Also fix naming as said in this comment https://github.com/foundry-rs/starknet-foundry/pull/2044#discussion_r1704078174

**Comment by Nemezjusz** [comment]
Hi, I would like to take on this issue. I have worked with StarkNet-Foundry before, and I believe I can solve it just as well as I did previously.
