### ISSUE TITLE
Document in appendix that `_global` cheatcodes work indefinetely 

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#2394]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

The name suggests that behavior, but it is not documented anywhere. We should update the docs to explain that more clearly.

**Comment by cptartur** [comment]
https://foundry-rs.github.io/starknet-foundry/appendix/cheatcodes/block_number.html

**Comment by ScottyDavies** [comment]
Hi @cptartur I am open to work on this?
