### ISSUE TITLE
derive copy on DeclareResult

### ISSUE THREAD

**Issue by enitrat** [foundry-rs/starknet-foundry#2395]
### Which component is your feature related to?

Forge

### Feature Request

```rust
#[derive(Drop, Serde, Clone)]
enum DeclareResult {
    Success: ContractClass,
    AlreadyDeclared: ContractClass,
}
```

-> 
```rust
#[derive(Drop, Serde, Copy)]
enum DeclareResult {
    Success: ContractClass,
    AlreadyDeclared: ContractClass,
}
```

There's no reason to be deriving Clone, when ContractClass derives Copy.

**Comment by ScottyDavies** [comment]
Hello @enitrat Please can you assign this task to me so I can start working on it immediately.

**Comment by ShantelPeters** [comment]
Hi @enitrat can i please be assigned to this issue?
