### ISSUE TITLE
Update gif in README

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#2405]
### Which components does the task require to be changed? (think hard pls)

other (describe below)

### Description

Right now, it shows a super outdated version of `snforge` that doesn't even require `snforge test`. Would be nice to update that.

**Comment by abhilov23** [comment]
Hii @cptartur, I would like to work on this. But I want more information regarding this.

**Comment by abhilov23** [comment]
Sir i am new to openDust, can you please guide me how can i access the application ?

**Comment by cptartur** [comment]
Duplicating #1712
