### ISSUE TITLE
Bump Scarb to `2.8.0`

### ISSUE THREAD

**Issue by integraledelebesgue** [foundry-rs/starknet-foundry#2426]
At the moment, Foundry uses Scarb `2.7.0` in `tool-versions`. Upgrading to `2.8.0` causes **a lot** of runtime errors in tests.
However a standard users' "create - declare - deploy" pipeline works fine.

**Comment by ksew1** [comment]
If you ever decide to bump it to 2.8.0 please unignore [this](https://github.com/foundry-rs/starknet-foundry/blob/0066f89af75f5543bbecd4b8116ef86139364bd0/crates/forge/tests/e2e/coverage.rs#L6) test

**Comment by Arcticae** [comment]
Discussed offline, closing for now
