### ISSUE TITLE
Improve Forge configuration acquired from `.toml`s

### ISSUE THREAD

**Issue by integraledelebesgue** [foundry-rs/starknet-foundry#2433]
### Which component is the issue related to?
Forge

### Issue
* Partially fixed by @piotmag769 in [PR](https://github.com/foundry-rs/starknet-foundry/pull/2432#issue-2497325264)
* Fork tests receive improper configuration (upper-case "Latest")
* Block id (e.g. "Latest") is hardcoded, we need to introduce constants
* Existing tests need to be improved
* We need to add e2e tests

**Comment by piotmag769** [comment]
>snforge.toml cannot conflict with Scarb.toml

There is no `snforge.toml` 🤔
