### ISSUE TITLE
Document that you need to install rust for plugin compilation

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2436]
### Which components does the task require to be changed? (think hard pls)

other (describe below)

### Description

You need to install rust in order to compile the plugin properly. 
There seem to be errors if you do it with a wrong one, it should be mentioned which one you should have:

![telegram-cloud-photo-size-4-5954002365629710954-y](https://github.com/user-attachments/assets/bdecbe0e-d798-4d68-8ab1-a5c1eb9a6e79)

**Comment by cptartur** [comment]
Duplicating #2452 already in progress
