### ISSUE TITLE
Update `storage-cheatcodes.md` guide

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2439]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

This guide is outdated since 2.7.0 introduced new abstractions for storage. 
Older version should be preserved for some time in case anyone wants to use that one.

**Comment by integraledelebesgue** [comment]
In fact, we need to update only [this section](https://foundry-rs.github.io/starknet-foundry/snforge-advanced-features/storage-cheatcodes.html#example-with-storage_address_from_base) because everything else works fine.
