### ISSUE TITLE
Handle contract redeclaration in `sncast_std` 

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2469]
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

We need `sncast_std` to be similar to snforges' so that if it fails with `ClassAlreadyDeclared` it carries a `ClassHash`, and we can carry on with the declaration

Or alternatively we can retrieve the state from chain and save it to the state file automatically

**Comment by cptartur** [comment]
This might be already partially resolved and needs to be investigated.

**Comment by gianalarcon** [comment]
Hi [starknet-foundry](https://github.com/foundry-rs/starknet-foundry) team, our project is still facing this issue. Waiting for this one to be solved. Thanks!!
