### ISSUE TITLE
Document that `casm = true` in Scarb.toml slows the compilation

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#2472]
### Which components does the task require to be changed? (think hard pls)

snforge, sncast

### Description

We compile every sierra with USC anyways since Scarb gives no guarantee about CASM by design.
The overhead generated by this can be huge for big sierra programs (couple dozens of MB). It was only mentioned changelog of 0.23.0 version.  It should be done in this file [here](https://github.com/foundry-rs/starknet-foundry/blob/master/docs/src/appendix/scarb-toml.md)

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry2).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer and will love to work on this

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Am a technical writer

### How I plan on tackling this issue
kindly assign ETA <= 78hrs

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

**Comment by Nemezjusz** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Hi, I am ICT student and for the last few months i was really intrested in Rust and Cario. I also work professionallyas software developer. I hope can help you solve this and start my journey in Cario world

### How I plan on tackling this issue
I’d locate Sierra compilation in snforge and sncast, address the USC and CASM overhead, and review version 0.23.0 changelogs for changes.

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
I have a solid background in software development, focusing on blockchain and toolchain optimization. My experience with various compilers, including StarkNet tools, allows me to manage complex build processes effectively. Additionally, my ability to write clear documentation will support updating the changelog and guiding users.

### How I plan on tackling this issue
I will analyze how snforge and sncast compile programs to identify delays in large Sierra compilations. I will find ways to improve memory usage, streamline the USC process, and add caching to reduce slowdowns. I will update the documentation and changelog for clear user instructions. Finally, I will thoroughly test the changes for efficiency in both small and large Sierra programs.

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Hello, can I be assigned to work on this issue?

I'm a software developer with over 4 years experience

Here's my OnlyDust profile https://app.onlydust.com/u/raizo07

ETA: One day

**Comment by ksew1** [comment]
@NueloSE any progress on this?

**Comment by NueloSE** [comment]
> @NueloSE any progress on this?

@ksew1, Am still trying to get a better understanding of the above task hope will make a PR over the weekend
