### ISSUE TITLE
Fix handling error messages in plugin

### ISSUE THREAD

**Issue by kkawula** [foundry-rs/starknet-foundry#2485]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

Error messages should display the entire variant structure e.g. [here](https://github.com/foundry-rs/starknet-foundry/blob/master/crates/snforge-scarb-plugin/tests/integration/single_attributes/fork.rs#L61) also should be added info about `url`

**Comment by cptartur** [comment]
@kkawula can you expand the task description?

**Comment by kkawula** [comment]
@cptartur Initially it was intended to improve diagnostic messages, but I can see that this problem should be redefined. I'm closing for this reason
