### ISSUE TITLE
Implement resource usage report

### ISSUE THREAD

**Issue by amanusk** [foundry-rs/starknet-foundry#249]
### To what component is your bug related to?

Forge

### Feature Request

Using the Blockifier, we can get the resource used for `invoke` transaction invocations.
Would be great to have a flag `--resource-report` to print out resources used (steps, built-ins etc)

**Comment by cptartur** [comment]
Thank you for the request. We are definitely considering adding transactions profiling at some point.

**Comment by Arcticae** [comment]
This should be considered as well on cairo level - which could enable users to assert gas consumed from a test.
I.e. a contract invocation would return gas consumed.

Also i think we should profile on transaction level and as well sum the transactions gas for a whole test (if a person wants to know the whole flows' cost)

**Comment by Arcticae** [comment]
Blocked by #327

**Comment by MaksymilianDemitraszek** [comment]
We could start by implementing it for a single test case as a whole as it will be the simplest. 

Later we could try to do it on a transaction level maybe something like this

```
let call_info = CallInfoDispatcher.get_balance()
assert(call_info.gas_usage < 100000, `above expected gas usage`)
assert(call_info.value == 5, `incorrect value`)
```

**Comment by enitrat** [comment]
Wouldn't it be better to have step counts rather than gas usage?

**Comment by MaksymilianDemitraszek** [comment]
@enitrat Sure but steps are only part of the picture as builtins can impose significant cost as well. Ideally we should report:
- steps
- builtins usage
- estimated gas

**Comment by enitrat** [comment]
> @enitrat Sure but steps are only part of the picture as builtins can impose significant cost as well. Ideally we should report:
> 
> * steps
> * builtins usage
> * estimated gas

yes, indeed, I just wanted to make sure we were not talking about Sierra Gas (I'm still not sure it's actually mapped to "real" execution resources)

**Comment by MaksymilianDemitraszek** [comment]
https://github.com/foundry-rs/starknet-foundry/issues/362 Should be taken under consideration

**Comment by Arcticae** [comment]
Related: #462

**Comment by piotmag769** [comment]
Blocked by #547
