### ISSUE TITLE
Support different account providers

### ISSUE THREAD

**Issue by war-in** [foundry-rs/starknet-foundry#253]
### To what component is your bug related to?

Cast

### Feature Request

We should consider supporting argent and bravos account creation

**Comment by THenry14** [comment]
let's add argent

**Comment by THenry14** [comment]
We should also think about where, and in what format, to store user info (especially since we will need to store more information, like class hashes, inside). 
Perhaps we could take a look at starkli keystore and try to support it as well?

**Comment by THenry14** [comment]
https://github.com/foundry-rs/starknet-foundry/issues/1854
