### ISSUE TITLE
Update `sncast` docs to use data transformer instead of serialized calldata as a default exampl

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#2557]
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

Once data transformer has proven itself to be working correctly we could update the documentation so default way of passing arguments is shown as data transformation. 

Current way of passing already serialized calldata could be documented as an option.

**Comment by cptartur** [comment]
Blocked: Let's wait until at least some time after data transformer is released.

**Comment by Mystic-Nayy** [comment]
@cptartur Can i be assigned to work on this?
