### ISSUE TITLE
Enable full overflow checks in data transformer

### ISSUE THREAD

**Issue by integraledelebesgue** [foundry-rs/starknet-foundry#2559]
## Component the issue is related to
Cast - data transformer

## Issue
At the moment, data transformer always analyzes the calldata according to ABI and tries to interpret it as a Cairo expression. If ABI-based transformation fails (in particular because of the overflow), it my succeed parsing it as an already serialized data. This leads to an invoke-time overflow error instead of transform-time.

See ignored test `sncast tests::integration::data_transformer::test_signed_fn_overflow` demonstrating such behaviour.

**Comment by cptartur** [comment]
@integraledelebesgue please update me on status of this

**Comment by integraledelebesgue** [comment]
There is no possibility to test a single numeric literal without a type suffix for overflow. It will become possible when we [add a flag disabling data transformation](https://github.com/foundry-rs/starknet-foundry/issues/2558)

**Comment by cptartur** [comment]
We no longer fallback to serialized data from transformer
