### ISSUE TITLE
Fix nonces in cheatable entry point for `call_contract`

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#258]
### To what component is your bug related to?

Forge

### Feature Request

In `build_transaction_context`, `nonce` returned is always zero, this should be fixed

**Comment by cptartur** [comment]
Changing the milestone to Cheatable starknet, I think it makes more sense there

**Comment by MaksymilianDemitraszek** [comment]
It should only be incremented when contract which user is testing is an account. ohterwise it should always be 0.

**Comment by war-in** [comment]
Why do you think so? Isn't it just the nonce of the contract invoking this call?

Or maybe your point is that this parameter will be useful only while testing an account contract.

**Comment by MaksymilianDemitraszek** [comment]
@war-in afaik that is the starknet specification. nonce gets incremented only for account contracts

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek i kind of agree on this one with Igor
