### ISSUE TITLE
Add link to new docs

### ISSUE THREAD

**Issue by kkawula** [foundry-rs/starknet-foundry#2580]
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

Add link to new `Importing Accounts` docs page in proper section at the `Creating And Deploying Accounts` page

**Comment by Gerson2102** [comment]
Hey can I work on this one? Can this be considered a good first issue? Seems easy.

**Comment by kkawula** [comment]
It was resolved in pr involving new docs `Creating And Deploying Accounts` page
