### ISSUE TITLE
Update asdf installation guide 

### ISSUE THREAD

**Issue by kkawula** [foundry-rs/starknet-foundry#2594]
### Which components does the task require to be changed? (think hard pls)

snforge, sncast

### Description

One of the possibilities of installing `starknet-foundry` is installing by `asdf`,
Lots of users don't know how to set `starknet-foundry` version in `asdf` properly, and they get such error while trying to use `snforge` or `sncast` without globally set tool version or without `.toolversions` file in working dir:
```sh
No version is set for command snforge
Consider adding one of the following versions in your config file at 
starknet-foundry 0.31.0
```
Update the guide section in docs by warning example and solution snippet.
Add an example for changing tool version.

**Comment by sprtd** [comment]
Would love to work on this!

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.

### How I plan on tackling this issue
My Approach includes:
- Review the current documentation on the implementation of asdf installation.
- Update the guide on asdf installation for users.
- Create a Pull Request (PR).
- Request for a Review.
- Make changes based on the Review of the PR.

**Comment by kkawula** [comment]
Hi @sprtd, I've assigned you

**Comment by kkawula** [comment]
Hi @sprtd it is planned on [ODHack 9.0](https://app.onlydust.com/hackathons/odhack-90)

**Comment by kkawula** [comment]
Hi @sprtd it is planned for [ODHack 9.0](https://app.onlydust.com/hackathons/odhack-90)

**Comment by cptartur** [comment]
This issue is reserved for ODHack. Please apply through the page as outlined there after the hack starts
https://app.onlydust.com/hackathons/odhack-90

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.

### How I plan on tackling this issue
i will update the asdf installation guide for `starknet-foundry` by including a clear warning and a solution snippet that explains how to properly set the `starknet-foundry` version. Specifically, I will add instructions on ensuring that users set the tool version either globally or within their project directory using the `.tool-versions` file to avoid errors like "No version is set for command snforge/sncast." The update will also include a practical example demonstrating how to add the tool version using `asdf global starknet-foundry 0.31.0` or `asdf local starknet-foundry 0.31.0` within the project directory. Additionally, I will ensure that the documentation clearly highlights the importance of having the correct tool version set. Once the changes are made, I will review and verify the updated guide to ensure it is easy to follow for users.
ETA - 2 days

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
I am a full-stack and Web3 developer with experience in blockchain tools like StarkNet and Cairo.  I have worked with Cairo, JavaScript, TypeScript, and Solidity, and I’m skilled in managing development environments and toolchain dependencies. I’ve also used package managers such as asdf, npm.

### How I plan on tackling this issue
To resolve the issue, I would first replicate it by using snforge or sncast in an environment without a global tool version or a .tool-versions file. After confirming the error, I would research how to properly set the StarkNet Foundry version with asdf, ensuring that users understand both global and local setups. I would then update the documentation with a warning about the error.

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
I am a web3 developer, I have expertise in smart contracts, decentralized technologies, and frameworks like React. I can build innovative dApps, contribute to open-source projects, educate others, and network with industry leaders to advance my career in the decentralized space.

ETA => 42HRS after being assigned

### How I plan on tackling this issue
To update the documentation for installing `starknet-foundry` via `asdf`, follow these steps:

1. **Identify Key Components:** Determine which sections of the `snforge` and `sncast` documentation need updates regarding the `asdf` installation process and version management.

2. **Create Warning and Example:** Add a warning in the relevant documentation sections to highlight the error message users encounter when no version is set. Provide a solution snippet that shows how to add a version to the `.tool-versions` file.

3. **Example of Version Change:** Include an example demonstrating how to change the tool version using `asdf` commands, ensuring users understand the correct syntax and steps to avoid errors.

4. **Review and Test Changes:** Ensure that all changes are clear, concise, and tested to verify they address user concerns effectively.

5. **Submit Changes:** Commit the updates to the documentation and notify relevant stakeholders for review.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo
 Some of the documentations I've done that were merged:

https://github.com/dojoengine/book/pull/308,
https://github.com/keep-starknet-strange/joyboy/pull/143,
https://github.com/Scaffold-Stark/ss2-docs/pull/31,
https://github.com/horuslabsio/Starknet-Scaffold/pull/94,
https://github.com/Hyle-org/examples/pull/15,


### How I plan on tackling this issue
To come up with a comprehensive and correct documentation I’ll take the following steps:
1.⁠ ⁠I’ll go to the relevant guide section in the documentation and add a warning section to inform users about the importance of setting the version correctly when using asdf for starknet-foundry. Then I’ll provide a detailed explanation of how to set the correct tool version for snforge and sncast.
2.⁠ ⁠⁠I’ll provide example snippet for .tool-versions and explain. I’ll demonstrate how to globally set the tool version and also provide a command to set it locally.
3.⁠ ⁠⁠I’ll include an example error message in the guide to show what users will see if the version isn’t set and a brief troubleshooting step to help them resolve it quickly.

Please assign me, I’m ready to work.

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Hello, can I be assigned to work on this issue?

I'm a software developer with over 4 years experience

Here's my OnlyDust profile https://app.onlydust.com/u/raizo07

ETA: One day

**Comment by cptartur** [comment]
Hey @od-hunter how's the progress on this?

**Comment by od-hunter** [comment]
> Hey @od-hunter how's the progress on this?

Hi @cptartur , I'm on it already, will push a PR soon.
