### ISSUE TITLE
Check internal packages formatting

### ISSUE THREAD

**Issue by franciszekjob** [foundry-rs/starknet-foundry#2596]
### Which components does the task require to be changed? (think hard pls)

other (describe below)

### Description

We have many internal packages (needed mostly for testing purposes, located in `crates/forge/tests/data`) and their formatting isn't checked. We could add step in CI which runs `scarb --fmt`.

**Comment by Benjtalkshow** [comment]
hello @franciszekjob 
Is this issue open for contribution? i would love to work on this issue. i use rust and i am confident i can fix this issue.
I will carefully configure the CI pipeline and ensure the packages in crates/forge/tests/data are properly set up and formatted. Thanks
