### ISSUE TITLE
Show using `snforge_std` and `sncast_std` from registry in docs

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#2599]
In various places in documentation, we show using `snforge_std` and `sncast_std` from `git`. We should instead show how to use them from package registry.

**Comment by Gift-Naomi** [comment]
@cptartur Please can I be assigned to work on this?

**Comment by od-hunter** [comment]
Hi @cptartur , please can I be assigned this?
I am a blockchain developer and I'm also good at documentations. Below are some of the documentations I've done that were merged:

https://github.com/dojoengine/book/pull/308,

https://github.com/keep-starknet-strange/joyboy/pull/143,

https://github.com/Scaffold-Stark/ss2-docs/pull/31,

https://github.com/horuslabsio/Starknet-Scaffold/pull/94,

https://github.com/Hyle-org/examples/pull/15,

Please I’m ready to work, assign me please.

**Comment by martinvibes** [comment]
hello @cptartur i would love to work on this issue please kindly  assign :)
