### ISSUE TITLE
Design simplified cast interaction flow

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#2603]

**Comment by Mystic-Nayy** [comment]
@cptartur I can work on this if you'd assign me.

**Comment by NueloSE** [comment]
@cptartur can i work on this task

**Comment by cptartur** [comment]
Sorry, we're not accepting submissions for this issue.

**Comment by cptartur** [comment]
Closing in favor of specific issues created #2696 #2695 #2221
