### ISSUE TITLE
Store/load not working correctly

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#2628]
From discord:
https://discord.com/channels/793094838509764618/1270120969880735744/1299018985328607365
https://discord.com/channels/793094838509764618/1270120969880735744/1300782111669616640

> Hey there I'm facing some issues to store an Option<u64>. When I load i get the good value but when call a function that read the storage it returns Option::None(()) 
Do you have any solutions to set option in storage ?

> Sure basically I have a contract with this storage :  withdrawal_pool_to_timestamp: Map<u256, Option<u64>>  and view function that returns the storage for a given u256.   In my test I store an option to the storage as follow  let mut keys: Array<felt252> = ArrayTrait::new();
    let current_epoch: u256 = 0;
    current_epoch.serialize(ref keys);
    let storage_address = map_entry_address(
        selector!("withdrawal_pool_to_timestamp"), keys.span()
    );
    let mut serialized_value_tim: Array<felt252> = ArrayTrait::new();
    let timestamp_with: Option<u64> = Option::Some((22));
    timestamp_with.serialize(ref serialized_value_tim);
    store(
        target: liquid_staking.contract_address,
        storage_address: storage_address,
        serialized_value: serialized_value_tim.span()
    );
  when I use the load cheat code using the same storage_address, I get the wanted result : Option::Some((22))  but when I call my view function using 0 as for mapping value, I get Option::None(())

**Comment by franciszekjob** [comment]
This should be fixed once https://github.com/foundry-rs/starknet-foundry/issues/2593 is resolved.

**Comment by franciszekjob** [comment]
Closing this as it's result of #2593

**Comment by franciszekjob** [comment]
Closing this as it's result of #2593

**Comment by franciszekjob** [comment]
As per [docs](https://docs.starknet.io/architecture-and-concepts/smart-contracts/serialization-of-cairo-types/#serialization_of_enums):

> Note that enum variants indices are 0-based, not to confuse with their storage layout, which is 1-based, to distinguish the first variant from an uninitialized storage slot.

The reason why `Option::Some(number)` isn't retrieved correctly using `read` is because it serializes to `[0, number]`. So instead of such way:

```rust
let mut serialized_value = ArrayTrait::new();
let value = Option::Some((100));
value.serialize(ref serialized_value);
```

we should use

```rust
let serialized_value = array![1, 100];
```

**Comment by franciszekjob** [comment]
As per [docs](https://docs.starknet.io/architecture-and-concepts/smart-contracts/serialization-of-cairo-types/#serialization_of_enums):

> Note that enum variants indices are 0-based, not to confuse with their storage layout, which is 1-based, to distinguish the first variant from an uninitialized storage slot.

The reason why `Option::Some(number)` isn't retrieved correctly using `read` is because it the serialized value is `[0, number]` while it should be `[1, number]`. So instead of such way:

```rust
let mut serialized_value = ArrayTrait::new();
let value = Option::Some((100));
value.serialize(ref serialized_value);
```

we can use

```rust
let serialized_value = array![1, 100];
```
