### ISSUE TITLE
Plugin macros should leave `\0` escaped

### ISSUE THREAD

**Issue by Draggu** [foundry-rs/starknet-foundry#2633]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

We basically want to do same as #2417 but for strings (`"` double quoted, as for `'` single quoted it is done in mentioned PR).

When passing any kind of strings we should NEVER use escaped versions compiler is exposing to us, instead use raw ones as we most of time (maybe all) are placing this string somewhere in generated code so it should be unchanged.

Add rich test case!

**Comment by Benjtalkshow** [comment]
I’m interested in this one.

**Comment by cptartur** [comment]
@Benjtalkshow hey, what's the status of this?

**Comment by Benjtalkshow** [comment]
> @Benjtalkshow hey, what's the status of this?

Still actively working on it.

**Comment by cptartur** [comment]
@Benjtalkshow Thank you for trying to contribute, but this has been resolved by the team already. Feel free to apply for other issues.
