### ISSUE TITLE
Refactor cheatable starknet backend

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#264]
### To what component is your bug related to?

Forge

### Feature Request

The target for us is to gather more contributors and make it easy for the users to write their code without much complexity and low-level stuff. This would require varying the abstraction levels, and somehow balancing it with keeping the code close to blockifier. Upstreaming some changes is also a valid approach in this task.

**Comment by piotmag769** [comment]
https://github.com/foundry-rs/starknet-foundry/pull/181#discussion_r1273384205

**Comment by Arcticae** [comment]
1. Refactor interface exposed to `forge` (hide implementation details) 
2. Expose some utilities for contributors, which might want to interact with VM in easier way

**Comment by Arcticae** [comment]
Blocked by #283
