### ISSUE TITLE
Rename `snforge init` to `snforge new`

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#2645]
`snforge init` behaves like `snforge new` - it creates a new directory instead of initializing an already existing one.

It should be renamed to `snforge new`.

This should be done in a non-breaking manner: Deprecated `snforge init` while adding `new` and only remove `init` after some time has passed since deprecation.

In the scope of this issue ensure that `scarb init` and `scarb new` works correctly when choosing the snforge test runner. Currently there is a problem with creating a new project when current working directory name is different than the provided name with the `--name` flag. Please see https://github.com/software-mansion/scarb/issues/1759 for reference.

**Comment by akintewe** [comment]
hello @cptartur  Can i please be assigned this issue
