### ISSUE TITLE
`sncast account create` should show copyable command for deployment

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#2667]
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

Right now, when `sncast account create` is used, it is unclear how to deploy the created account.
The output already indicates that the account needs to be prefunded but doesn't show how to do so.

Change `sncast account create` output, so it also includes a ready to copy command for declaring. The arguments like `--url` that are provided by the user should be captured and included in the output command so it can be copied and run.

Concept:

```shell
$ sncast account create --url my_url.xyz --name my_account
add_profile: --add-profile flag was not set. No profile added to snfoundry.toml
address: 0x075c4094d5431fea3bdfa1c65d393ea52315f513b9fa81d1466edf1d91fc4022
max_fee: 4241681639235
message: Account successfully created. Prefund generated address with at least <max_fee> STRK tokens or an equivalent amount of ETH tokens. It is good to send more in the case of higher demand.

After prefunding the address run:
sncast account deploy --url my_url.xyz --name my_account --fee-token strk 
```

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue @cptartur

**Comment by cptartur** [comment]
Hey, thanks for applying, however we mostly accept applications for tasks marked with "help wanted" or "good first issue" label.
