### ISSUE TITLE
Default account mechanism for sncast

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#2695]
Currently, `--account` must must be always provided in sncast. It can be done through CLI or `snfoundry.toml` file. 

#2221 will allow defining a default account for all sncast projects. This is not very well integrated with our account commands though.

Add an interactive prompt to `account import` and `account create` that will prompt the user to make the account they imported default. It should be something like this

```shell
> Do you want to set the imported (created) account as default?
Yes
No
Don't ask again
```

On selecting `Yes`, user should be informed that the default was stored in global config and how to find/change it.

Additionally, `account list` should indicate which account is set as a default.

If using `sncast` command which requires `--account`, in case the flag is missing, the output should be updated to provide an information about setting the default account.

**Comment by codeWhizperer** [comment]
@cptartur can I work on this?
