### ISSUE TITLE
Pass `current_dir` to runner

### ISSUE THREAD

**Issue by war-in** [foundry-rs/starknet-foundry#271]
> Internal test improvement. Does not affect users

We should allow passing and setting `current_dir` in the runner function in tests https://github.com/foundry-rs/starknet-foundry/blob/master/crates/cast/tests/helpers/runner.rs.

That way we would be able to better test some of sncast features (like declaring contract without explicitly stating the path to Scarb.toml). This change should also simplify our test setup.

**Comment by dubzn** [comment]
Hi! Is this available? Can i take it?

**Comment by war-in** [comment]
Yup, would be nice to have it done 🔥

**Comment by THenry14** [comment]
Hi @dubzn !
Hope everything's going well! Just wanted to touch base regarding this issue. If you need any input, run into questions, or would like to discuss anything, feel free to reach out. We're here to support you if you run on any blockers :) cheers!

**Comment by THenry14** [comment]
Hi @dubzn , haven't heard from you in a while so for now I'm going to unassign you from this issue, so it is not blocked for others. If you'd still like to work on this please let me know, and if the issue is still available I'll re-assign you :)
