### ISSUE TITLE
`snfoundryup` for updating snfoundry

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#275]
We should think about adding some mechanism, to simply update forge and cast binaries.
One approach could be to copy `rustup` behaviour.

**Comment by kontrol-apa** [comment]
Hello, i would like to take over if this is still open. I am thinking about modifying the foundryup from [foundry-rs](https://github.com/foundry-rs/foundry/tree/master/foundryup) to provide the same functionality

**Comment by kontrol-apa** [comment]
@THenry14 this is addressed by https://github.com/foundry-rs/starknet-foundry/pull/1041
