### ISSUE TITLE
Get current configuration

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#278]
We should add a possibility, to quickly determine with what configuration we are currently running. It could be useful to make double sure some calls someone tries to make are done from specific configuration, eg something like:

```
$ sncast show-config
network: example
account: example
url: http://example.com
(...)
```

There should be a new subcommand added - `show-config`, that prints out (if set) currently used:
- profile
- network
- rpc url
- account
- path to scarb toml
- accounts file path

Here's an example, existing command: https://github.com/foundry-rs/starknet-foundry/blob/621a1a5abb49fe41f459f655901cff0c915809e8/crates/cast/src/starknet_commands/call.rs#L12

All commands are parsed and executed from main: https://github.com/foundry-rs/starknet-foundry/blob/621a1a5abb49fe41f459f655901cff0c915809e8/crates/cast/src/main.rs#L81

**Comment by btc-icosahedron** [comment]
can I try this one?

**Comment by THenry14** [comment]
sure :)
