### ISSUE TITLE
Remove nonce test

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#292]
There are some ignored tests in the `starknet.rs` integration test file. They should be removed, since nonce implementation is going to remain the same for the time being.

**Comment by MaksymilianDemitraszek** [comment]
@cptartur More description would be appreciated, why we have to remove something from starknet.rs?

**Comment by cptartur** [comment]
`starknet.rs` integration tests, not the library. It has some commented out tests.
