### ISSUE TITLE
Refactor forge so test summaries are extracted to a separate module

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#294]
_Originally posted by @piotmag769 in https://github.com/foundry-rs/starknet-foundry/pull/257#pullrequestreview-1547653842_

`TestFileSummary` struct and related implementations/helpers should be moved to a separate `pub(crate)` module within forge.

https://github.com/foundry-rs/starknet-foundry/blob/ceaf6c507d04922aecafe8ac1efb684a029d34ea/crates/forge/src/lib.rs#L269

**Comment by piotmag769** [comment]
Extract `TestFileSummary` struct and its `impl` to a separate file from [lib.rs])https://github.com/foundry-rs/starknet-foundry/blob/master/crates/forge/src/lib.rs)
