### ISSUE TITLE
Track all changes from PRs in CHANGELOG.md

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#302]
### To what component is your bug related to?

Other (Please describe below)

### Feature Request

We should have a changelog file, in which we incrementally add the changes relevant for the users. 
This will make releasing easier, for people unaware of every single change in the project.
The task should also include modifying our PR template, to add updating/considering updating changelog in the process.

**Comment by piotmag769** [comment]
@Arcticae I think it is done?
