### ISSUE TITLE
Add caching of vm memory for info segments

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#304]
In cheatnet, in the following function:
https://github.com/foundry-rs/starknet-foundry/blob/621a1a5abb49fe41f459f655901cff0c915809e8/crates/cheatnet/src/rpc.rs#L513

Instead of creating the segment for every time the function is called, here:
https://github.com/foundry-rs/starknet-foundry/blob/621a1a5abb49fe41f459f655901cff0c915809e8/crates/cheatnet/src/rpc.rs#L558

We should make a similar function to the blockifier's syscall_processor counterpart which we're mocking:
https://github.com/starkware-libs/blockifier/blob/0212ac4b4c9ac6e3efc8e9e8bf028ff6b0004e2c/crates/blockifier/src/execution/syscalls/hint_processor.rs#L269
So that it either returns or creates a new one (if it doesn't exist yet)

Remember to add tests with `stop_roll`/`stop_warp` variants, as it might break the behavior potentially ⚠ 
Make sure to test the caching as well

**Comment by Arcticae** [comment]
Blocked by #303

**Comment by cptartur** [comment]
@Arcticae can you please expand the task description?

**Comment by Arcticae** [comment]
> can you please expand the task description

Done, can you verify if that's sufficient @cptartur?

**Comment by cptartur** [comment]
I think it's okay. It will still require a bit of thinking about the exact documentation, but it should probably be clear enough.
