### ISSUE TITLE
Add cheatcode to fetch contract ClassHash

### ISSUE THREAD

**Issue by amanusk** [foundry-rs/starknet-foundry#335]
### To what component is your bug related to?

Forge

### Feature Request

Add a cheat code to get the current class hash of a given contract address. This is needed, in part, to test the replace class functionality

**Comment by cptartur** [comment]
Cannot the class hash returned by the `declare` method be used directly? I'm unsure what's the exact use case of that cheatcode would be.

**Comment by amanusk** [comment]
The usecase is to test the replace_class syscall.
The syscall replaces the class of the implementation after the class is already declared.
You want to be able to test the syscall worked and the contract is indeed updated and using the implementation you are expecting

**Comment by cptartur** [comment]
Okay, I get it. I think it makes sense to add this.

**Comment by vic-Gray** [comment]
I'd love to give this a go.

**Comment by GideonBature** [comment]
Could I try solving this?

My name is Gideon Bature, a Software Engineer. I have experience working with JavaScript/TypeScript, Rust and Cairo. If assigned this issue, I will send my first PR within 72 hours. Thank you!

**Comment by ryzen-xp** [comment]
Is this issue still available?

**Comment by OWK50GA** [comment]
Could I take a shot at this?

**Comment by aidenwong812** [comment]
I'd like to handle this task.

**Comment by olisaagbafor** [comment]
Could I take on this issue?

**Comment by emarc99** [comment]
May I try my hand at this?

**Comment by Supa-mega** [comment]
Is this issue still available? first time contributor
