### ISSUE TITLE
test if stop_cheatcode works properly in proxy calls, library calls and constructors

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#341]
We should make sure the address/block number changed to the previous one (applies to all prank and roll) after stop cheatcodes are merged

```
let a = call get_block_number

start_roll 234
let x = call get_block_number
assert x == 234

stop roll
let b = call_get_block_number

assert a == b
```

_Originally posted by @piotmag769 in https://github.com/foundry-rs/starknet-foundry/pull/329#discussion_r1279021365_

**Comment by piotmag769** [comment]
For newcomers: this task is about adding missing integration tests to prank and roll (`prank.rs` and `roll.rs` files from https://github.com/foundry-rs/starknet-foundry/tree/master/crates/forge/tests/integration). The tests should check if after stopping the prank/roll the caller address/block number changed to the previous one

**Comment by piotmag769** [comment]
@cptartur @Radinyn was it included in cheatnet tests?
