### ISSUE TITLE
`store`, `load` cheatcodes

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#346]
Cheatcodes manipulating storage

**Need resolving before this is started:**

- [x] #512 

## Important sidenote:

We should also, consider making a PR to the compiler to avoid having to use 
`create_state_for_testing()`, since the address info is known statically and can be determined separately, i.e.

`Dispatcher.storage_addresses().<var_a>.address()`
instead of 
`Dispatcher.get_state_for_testing().<var_a>.address()`

And `storage_addresses` would return a trait which does not allow mutating the variables, but only returns their relative addresses.

**Comment by Arcticae** [comment]
This is blocked by the `Layout` trait implementation in the compiler, which might help to improve UX of the storage operations.

**Comment by Arcticae** [comment]
It is planned to be implemented in the compiler, no tracking issue for now

**Comment by MaksymilianDemitraszek** [comment]
Giving the context for future reader, we need a layout trait as currently to extract storage types `create_state_for_testing` has to be used, and it creates unnecessary test state as we need only static stuff.
