### ISSUE TITLE
Replace default transaction hash in deploy with actual calculations

### ISSUE THREAD

**Issue by Radinyn** [foundry-rs/starknet-foundry#358]

**Comment by MaksymilianDemitraszek** [comment]
If it is not available in transaction info then it is not a problem. Can you check it @Radinyn and close if it is not a problem? 🥺

**Comment by cptartur** [comment]
I think what can be problematic is that we are using same class hashes for multiple transactions. E.g. `declare` always uses `TransactionHash::default()`.
