### ISSUE TITLE
Support for e2e tests in cairo with devnet

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#389]
On Starknet, when calling contracts using `starknet_call` RPC method (without an account) info methods like `get_caller_address` etc. return default valeus e.g. `0`. There is no transaction and block context.

However this is impossible to do in Starknet Foundry. It doesn't matter if the method accepts `@ContractState` or `ref ContractState`, we are always executing the method in cheated context - all cheatcoded values are present,`get_caller_address` returns non 0 value etc.

It should be possible to emulate `starknet_call` in Foundry. We should either change the behavior of Dispatchers or introduce a separate method for just calling contracts.

**Comment by cptartur** [comment]
I think it should be at least noted somewhere in the docs that calling in forge never behaves like `starknet_call` rpc method because it's not obvious. And I think protostars `call` did behave like an rpc call, so it may be confusing for the users migrating from that tool. 

> We could consider introducing additional target #devnet-tests (name TBD) which could provide call and invoke dispatchers and take targetted devent url as argument which those be executed on

We should definitely support that somehow.

**Comment by MaksymilianDemitraszek** [comment]
> And I think protostars call did behave like an rpc call, so it may be confusing for the users migrating from that tool.
Cairo 1 Protostar did, Protostar 0 didn't

**Comment by Arcticae** [comment]
Isn't this related to #18 somehow? 
We could run deployment scripts on a local node and achieve the behavior you mean @cptartur

**Comment by Arcticae** [comment]
Moving this to `general`

**Comment by cptartur** [comment]
This task is mostly about the whole discussion about the call/invoke architecture in tests as well as stateful tests. Not sure what component it should be attached to, perhaps both cheatnet and forge?

**Comment by piotmag769** [comment]
Is it still relevant? @cptartur @MaksymilianDemitraszek

**Comment by cptartur** [comment]
I think it kind of still is? In case we want to add some tests in the future that are not in the invoke transaction context.

**Comment by MaksymilianDemitraszek** [comment]
Renaming it to be more accurate

**Comment by cptartur** [comment]
Duplicate of #1033
