### ISSUE TITLE
Reconsider the usage of `unwrap` and `Result` in cheatcodes

### ISSUE THREAD

**Issue by Radinyn** [foundry-rs/starknet-foundry#391]
Currently we use a random mix and match of all approaches, instead we should:
- panic (`expect`, `unwrap`) on things that should never happen (this will shut down the whole runner)
- return a `Result` in Rust on things that should always fail a single test case
- return a `Result` in Cairo on things that the user could want to handle

**Comment by Arcticae** [comment]
@Radinyn isn't it in progress already?

**Comment by Radinyn** [comment]
#419
