### ISSUE TITLE
Document exactly what the cheated methods are changing

### ISSUE THREAD

**Issue by Radinyn** [foundry-rs/starknet-foundry#392]
To make sure we are capable of keeping `Cheatnet` up to date we need to have a clear understanding of the modified foreign code.

**Comment by cptartur** [comment]
The code in cheatable starknet should be compared with the code of https://github.com/starkware-libs/blockifier. Code sections that have been changed compared to blockifier should be clearly marked with comments so we can easily see the modified code.
