### ISSUE TITLE
Hoist common dependencies to the workspace, remove unused ones

### ISSUE THREAD

**Issue by Radinyn** [foundry-rs/starknet-foundry#394]
When `Cheatnet` separated from `Forge` some unused and shared dependencies were left in the `Cargo.toml` files.

**Comment by Utilitycoder** [comment]
I will like to handle this issue.

**Comment by Utilitycoder** [comment]
Hi again, I am literally a green-horn when it comes to oss. Can you please provide more details on how you want the issue fix and specifically what needs to be done?
