### ISSUE TITLE
Create a crate for handling starknet_artifacts.json file from scarb

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#41]
https://github.com/software-mansion/protostar/issues/2141

We're handling starknet_artifacts.json file both in all our components. Code for deserializing and handling this file could be moved to a separate crate and used in all of those projects.

Should include swapping code parts in Cast/Forge/Cheatnet which parse the artifacts

**Comment by Arcticae** [comment]
@cptartur we'd like to do this sooner than later 😬

**Comment by Radinyn** [comment]
by #484
