### ISSUE TITLE
Decouple snforge from scarb version

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#417]
Generally we should introduce `test` target in scarb and move our test collection logic there. Scarb should produce casm binaries for each test target. forge should load them and execute. Scarb has to introduce artifacts file to include necessary metadata.

Should be synced with scarb team beforehand.

**Comment by piotmag769** [comment]
Related scarb PR: https://github.com/software-mansion/scarb/pull/886
