### ISSUE TITLE
`setup-snfoundry` CI workflow action

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#422]
It should take `snfoundry-version` as an argument.

**Comment by MaksymilianDemitraszek** [comment]
Should take inspiration from https://github.com/software-mansion/setup-scarb , if somebody wants to work on this one let us know on telegram we will help to set up the repository

**Comment by binsta** [comment]
@MaksymilianDemitraszek  I'm in

**Comment by Arcticae** [comment]
@binsta i've just created a repo for this:
https://github.com/foundry-rs/setup-snfoundry
Feel free to submit PRs :)
