### ISSUE TITLE
Improve cast tests (creating directories)

### ISSUE THREAD

**Issue by war-in** [foundry-rs/starknet-foundry#436]
In some cast tests, we are creating directories, but often we are not using tempdirs. As a result, junk folders remain after a failed test run. 
https://github.com/foundry-rs/starknet-foundry/blob/c04585092890f3cd351b36b411a4dae651c35feb/crates/cast/tests/helpers/fixtures.rs#L173
https://github.com/foundry-rs/starknet-foundry/blob/c04585092890f3cd351b36b411a4dae651c35feb/crates/cast/tests/e2e/account/create.rs#L134
https://github.com/foundry-rs/starknet-foundry/blob/c04585092890f3cd351b36b411a4dae651c35feb/crates/cast/tests/e2e/account/deploy.rs#L103

We should always use tempdirs when dynamically creating directories. `tempfile` or `tempdir` crates can be used for this.

**Comment by partychad** [comment]
If this issue is still available, i would love to work on it :)

**Comment by war-in** [comment]
@THenry14 ? 🙏

**Comment by THenry14** [comment]
Sure, assigned :+1:
