### ISSUE TITLE
Unit testing includes keccak call crash

### ISSUE THREAD

**Issue by zkcarter** [foundry-rs/starknet-foundry#440]
### To what component is your bug related to?

Forge

### Foundry Version

v0.3.0

### What operating system are you using?

Linux

### What system architecture are you using?

x86

### What happened

I have several unit tests, and the test code calls the keccak-related function interfaces in the cairo corelib. These tests are crashing this time like this:

```
Collected 1 test(s) and 1 test file(s)
Running 1 test(s) from src/lib.cairo
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExpectedInteger(Relocatable { segment_index: 10, offset: 2 })', crates/forge/src/cheatcodes_hint_processor.rs:370:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After locating the issue, I found that it is related to the invocation of keccak. 

**Steps of Reproduction**

You can try running the built-in test cases for keccak in the cairo corelib, which can be found [here](https://github.com/starkware-libs/cairo/blob/main/corelib/src/test/keccak_test.cairo#L41). 

Although the `cairo_keccak` method is a new function added in v2.1.0, I still encounter the same issue when manually calling `keccak_syscal` prior to this version.

### Trace

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExpectedInteger(Relocatable { segment_index: 10, offset: 2 })', crates/forge/src/cheatcodes_hint_processor.rs:370:50
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1651:5
   3: <forge::cheatcodes_hint_processor::CairoHintProcessor as cairo_vm::hint_processor::hint_processor_definition::HintProcessorLogic>::execute_hint
   4: cairo_vm::vm::vm_core::VirtualMachine::step
   5: cairo_vm::vm::runners::cairo_runner::CairoRunner::run_until_pc
   6: cairo_lang_runner::casm_run::run_function
   7: cairo_lang_runner::SierraCasmRunner::run_function
   8: forge::run
   9: snforge::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by glihm** [comment]
@zkcarter how are you testing keccak?

I've tested also today in a project, I can't call any function that calls `keccak_syscall` directly from test as it's not supported (yet?).

But deploying a test contract and then calling keccak gives the expected results. :+1:
Just for now, ensure that your test contract is not under `#[cfg(test)]` to be able to use `declare('your_contract')`.

(I am working on the main branch a798efb, compiled locally).

**Comment by zkcarter** [comment]
@glihm 
Hello, the issue I am currently encountering is testing the keccak function using unit testing (not integration testing, so there is no contract deployment).
