### ISSUE TITLE
Update snforge template before precalc_addr release

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#450]
Has to be done on the release day. Consider making manual template releases

**Comment by cptartur** [comment]
Can you elaborate on that @piotmag769?

**Comment by piotmag769** [comment]
@cptartur Basically we need to update the template since we did a breaking change in how the standard deploy flow has to be written (`contract.deploy(@calldata)`), but it has to be done just before the release to not confuse users
