### ISSUE TITLE
Consider adding a note about the possibility of applying a cheatcode to a contract/function that doesn't exist

### ISSUE THREAD

**Issue by abulenok** [foundry-rs/starknet-foundry#464]
Refers to `roll`, `prank`, `warp` cheatcodes

**Comment by cptartur** [comment]
What exactly do you mean by this? Is there any usecase of rolling, etc. a contract that does not exist? Especially since some (all?) of them do not work in constructors yet #254

**Comment by abulenok** [comment]
relevant discussion https://github.com/foundry-rs/starknet-foundry/pull/385#discussion_r1284045846

**Comment by cptartur** [comment]
Is this still relevant if we have this in docs already? https://foundry-rs.github.io/starknet-foundry/testing/using-cheatcodes.html#pranking-the-constructor
