### ISSUE TITLE
Extract conversions to a separate crate

### ISSUE THREAD

**Issue by Radinyn** [foundry-rs/starknet-foundry#489]
The conversions listed in `conversions.rs` file 

https://github.com/foundry-rs/starknet-foundry/blob/621a1a5abb49fe41f459f655901cff0c915809e8/crates/cheatnet/src/conversions.rs#L8

Should be moved to a separate crate (like `cheatnet` and `forge`). 
They also should be unified to use a reference to an object, and return a new object (so that they don't `drop` the used value, for convenience). Adding more unit tests is strongly encouraged.

**Comment by war-in** [comment]
there is one 
```
contract_address_from_felt252
```

**Comment by Arcticae** [comment]
@war-in i think it's no longer the case and it's been changed
