### ISSUE TITLE
Deploying contracts with predefined address

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#496]
Adding an option of deploying contracts with a specific predefined address could be useful for instances like testing interactions with UDC or ETH ERC20 contract or any other contract that has consistent address in Starknet and realistically could be hardcoded in the source code.

**Comment by cptartur** [comment]
This also requires some support on cheatnet side. If we decide to start working on this, it would make sense to split into 2 issues for both components.

**Comment by Arcticae** [comment]
@cptartur can you reference which issue is this being blocked by?

**Comment by Arcticae** [comment]
Related:
[543](https://github.com/foundry-rs/starknet-foundry/issues/543)

**Comment by Arcticae** [comment]
Moving this to `general`, can you create an issue @piotmag769 for this in cheatnet and mark it blocked & dependent on #543
