### ISSUE TITLE
Add `account delete` command

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#498]
### To what component is your feature request related to?

Cast

### Feature Request

It would be nice to have:
- `account delete` 

Someone could delete an existing account from the `accounts-file` with such a command. A new file named `delete.rs` should be added to https://github.com/foundry-rs/starknet-foundry/tree/c04585092890f3cd351b36b411a4dae651c35feb/crates/cast/src/starknet_commands/account and included in mod.rs placed there. 

This new command should take additional arguments in the form of flags:
- `--name` - a name of an account to be added (required)
- `--network` - a chain id of the network where account to be added was deployed (optional - if not passed we should require --url or --profile with configured rpc url to be passed to cast)

The command should take all the necassary info and remove the account (with all its data) from the accounts file specified by the user using flag `--accounts-file` passed to cast. An example of a command would be:

```
sncast --accounts-file ~/myfile.json account delete --name mariusz --network alpha-goerli
```

**Comment by devnet0x** [comment]
Please assign me this issue

**Comment by THenry14** [comment]
Hi @devnet0x , Hope everything's going well! Just wanted to touch base regarding this issue. If you need any input, run into questions, or would like to discuss anything, feel free to reach out. We're here to support you if you run on any blockers :) cheers!

**Comment by devnet0x** [comment]
Hi, thanks. It's my first rust contribution so it has been a little hard...:)...but now i'm testing mi changes so i will be asking very soon.
