### ISSUE TITLE
Add `--force-rebuild` flag to declare

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#500]
By default, if sncast finds that contract that's to be declared is already built, it won't rebuild it and use the compiled artifacts for contract's declaration. We should add a flag `--force-rebuild` to `sncast declare` command, to force a contract rebuild in such situation. 

Proposed solution is to check the target directory in scarb metadata and remove it.

**Comment by cptartur** [comment]
Is this true that contract's aren't always rebuilt? I've looked at code of https://github.com/foundry-rs/starknet-foundry/blob/master/crates/cast/src/starknet_commands/declare.rs declare and it seems that `scarb build` is always called.

Or should this be added as part of this task as well?

**Comment by THenry14** [comment]
@cptartur try running tests once and you'll see that every test contract is being built. Then run it again, and they are not (because artifacts are already there). My bet is that this is something that scarb does. The issue is problematic especially when we update scarb version or modify Scarb.toml - the tests then fail, unless we remove artifacts manually (thus, forcing rebuild) like so: `cast $ find tests/data/contracts -type d -name "target" -exec rm -r {} +`

**Comment by THenry14** [comment]
Tried to reproduce the issue with recent scarb versions but couldn't, so this can be closed.
