### ISSUE TITLE
Write a design document on `store` and `load` cheatcodes

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#512]
Create a design document proposing the interface of the cheatcodes `store` and `load` for purpose of modifying the contract storage.

**Comment by cptartur** [comment]
I think this one is free to take, with a disclaimer that the review of a design document can/will be much longer and nit-pickier process that that of the standard PR. 

If this is fine by you @glihm I can assign this one to you.

**Comment by cptartur** [comment]
Hey @glihm, should I assign this to you?

**Comment by glihm** [comment]
Hey @cptartur! If nobody at SWM is actively on it, yes I would be happy to propose something. :+1:

**Comment by glihm** [comment]
@cptartur very sorry mate as seen in TG with Pitor, I'm still struggling finding time for this. Could you please unassigned me to ensure I'm not blocking the progress.

Thanks a lot again for the follow up from SWM. :pray:
