### ISSUE TITLE
Add init command to forge

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#515]
### Which component is your feature related to?

Forge

### Feature Request

Add a command/flag to forge that will create a new project using https://github.com/foundry-rs/starknet_forge_template

Note: we cannot use `snforge init` because first argument is used to filter test by their name. Some possible solutions: add a flag like `--init`, add a separate command like `snforge-init`, etc.

**Comment by Radinyn** [comment]
Should we consider `snforge test` and `snforge init`? Command abstraction may be helpful in the future.

**Comment by cptartur** [comment]
> Should we consider `snforge test` and `snforge init`? Command abstraction may be helpful in the future.

We can discuss it, but I though that not requiring the user to pass any other command after `snforge` to run tests is quite practical - realistically the user want's to just run tests 99% of the time.
