### ISSUE TITLE
Add a more relatable example for using cheatcodes in the constructor

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#521]
### Which component is your feature related to?

Forge

### Feature Request

For now, we present all of the cheatcodes behavior using `prank` as an example, but using `roll`/`warp` would be more practical for users to comprehend the nature of the "mocking constructor" flow.

As a part of this task you should:
- Delete the old example
- Write a contract and a test that uses this behavior (with comments preferably)
- Explain to the user in documentation how this works and what it can be used for

**Comment by Arcticae** [comment]
> Can I take this? @Arcticae

Yes, please do! :)

**Comment by piotmag769** [comment]
Still willing to take this? @robertkodra

**Comment by robertkodra** [comment]
@piotmag769 sorry about this, was planning to finish it this weekend, however you can take it if you want.

**Comment by piotmag769** [comment]
Np, just wanted to make sure, feel free to take it!
