### ISSUE TITLE
Allow disabling colors in forge output

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#528]
Add `--color` flag to forge, similar to `cargo test` flag, that allows disabling or enabling coloring the output of `snforge.
It should have the following options:

- always - always use color
- never - never use color, disable all coloring

This flag should be added to `TestRunnerConfig` https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/report-time.html 
Argument and necessary logic configuring if coloring is used should be added to `print_test_result` function https://github.com/foundry-rs/starknet-foundry/blob/ceaf6c507d04922aecafe8ac1efb684a029d34ea/crates/forge/src/pretty_printing.rs#L41 and passed accordingly to usages of it.

**Comment by piotmag769** [comment]
It should be done by setting `CLICOLOR` env var, as `console` crate suggests https://docs.rs/console/latest/console/fn.colors_enabled.html

**Comment by cptartur** [comment]
> Hi, can I work on this one?

Sure, assigning you this one.

**Comment by ptisserand** [comment]
Should the `--color` flag enable/disable all colors output (including scarb) or only the test results ?

**Comment by cptartur** [comment]
> Should the `--color` flag enable/disable all colors output (including scarb) or only the test results ?

If we can disable color of scarb output in reliable way I think it should disable all outputs.

**Comment by ptisserand** [comment]
> > Should the `--color` flag enable/disable all colors output (including scarb) or only the test results ?
> 
> If we can disable color of scarb output in reliable way I think it should disable all outputs.

As suggested by @piotmag769 in https://github.com/foundry-rs/starknet-foundry/issues/528#issuecomment-1695574650_ it can be done by setting `CLICOLOR` for current process

**Comment by cptartur** [comment]
> > > Should the `--color` flag enable/disable all colors output (including scarb) or only the test results ?
> > 
> > 
> > If we can disable color of scarb output in reliable way I think it should disable all outputs.
> 
> As suggested by @piotmag769 in [#528 (comment)](https://github.com/foundry-rs/starknet-foundry/issues/528#issuecomment-1695574650)_ it can be done by setting `CLICOLOR` for current process

Though it would require modifying the environment of the user to do so, not sure about that. 

cc @piotmag769

**Comment by ptisserand** [comment]
Hum do you mean it's better to check `CLICOLOR` value before setting the value instead of doing something like this?:
```rust
fn test_workspace(args: TestArgs) -> Result<bool> {
    match args.color {
        ColorOption::Never => env::set_var("CLICOLOR", "0"),
        _ => (),
    }
    /* ...... */
 }
 ```

**Comment by cptartur** [comment]
I think it's better to check if. If we change the `CLICOLOR` env var, it will change the behavior for all other apps supporting this variable, and it's probably not the intended behavior for the users.

Perhaps let's just try to configure coloring just for snforge outputs and then we can think about scarb.

**Comment by ptisserand** [comment]
> I think it's better to check if. If we change the `CLICOLOR` env var, it will change the behavior for all other apps supporting this variable, and it's probably not the intended behavior for the users.
> 
I think the expected behavior is the following: when using `--color=never` no color output on stdout (`snforge` output and any child process putput)

Setting `CLICOLOR` in `snforge` process should not changed this environment variable value in `snforge` parent process.

**Comment by cptartur** [comment]
> > I think it's better to check if. If we change the `CLICOLOR` env var, it will change the behavior for all other apps supporting this variable, and it's probably not the intended behavior for the users.
> 
> I think the expected behavior is the following: when using `--color=never` no color output on stdout (`snforge` output and any child process putput)
> 
> Setting `CLICOLOR` in `snforge` process should not changed this environment variable value in `snforge` parent process.

Okay, maybe I'm just confused about env vars. If it doesn't affect the parent, we can go with setting `CLICOLOR`.
