### ISSUE TITLE
Test if `stop_warp` behaves correctly in library and proxy calls

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#531]
`warp_proxy` https://github.com/foundry-rs/starknet-foundry/blob/ceaf6c507d04922aecafe8ac1efb684a029d34ea/crates/cheatnet/tests/cheatcodes/warp.rs#L125 and `warp_library_call` https://github.com/foundry-rs/starknet-foundry/blob/ceaf6c507d04922aecafe8ac1efb684a029d34ea/crates/cheatnet/tests/cheatcodes/warp.rs#L152 tests should be extended to include stopping the warp after the `assert_success` and verification if block_timestamp returned to a default value (no value is retained after warp is cancelled).

**Comment by nestorbonilla** [comment]
I'll work on this.

**Comment by piotmag769** [comment]
Still willing to take this @nestorbonilla?
