### ISSUE TITLE
Extract `print` function from `cheatcodes_hint_processor` to a separate module

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#532]
`print` function https://github.com/foundry-rs/starknet-foundry/blob/ceaf6c507d04922aecafe8ac1efb684a029d34ea/crates/forge/src/cheatcodes_hint_processor.rs#L552 used by forge_print cheatcode should be extracted to a separate module, similar to `file_operations.rs` https://github.com/foundry-rs/starknet-foundry/blob/ceaf6c507d04922aecafe8ac1efb684a029d34ea/crates/forge/src/cheatcodes_hint_processor/file_operations.rs#L1

**Comment by devnet0x** [comment]
gm...may i take this issue?

**Comment by cptartur** [comment]
> gm...may i take this issue?

Sure! But it may make sense to either wait until #1030 is merged or base your branch of this PR since it's introducing quite a lot of changes to the package structure.
