### ISSUE TITLE
Add a short description to each cheatcode

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#550]
On the `Cheatcodes reference` page, we list all possible cheatcodes. However, to figure out which cheatcode does what, one has to open each link and read their description. This is problematic for new users trying to figure out features of forge.

https://github.com/foundry-rs/starknet-foundry/blob/master/docs/src/appendix/cheatcodes.md

Add a simple description to each link on the `cheatcodes.md` page.

e.g. 

* `start_prank` - change the caller address for a contract

**Comment by robertkodra** [comment]
Hi! Can I work on this?

**Comment by cptartur** [comment]
Sure! Assigning you.

**Comment by vvarl0cks** [comment]
still open? can you assign me. thanks.
