### ISSUE TITLE
Refactor `RunnerStatus`

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#552]
`RunnerStatus` https://github.com/foundry-rs/starknet-foundry/blob/621a1a5abb49fe41f459f655901cff0c915809e8/crates/forge/src/lib.rs#L60 should be renamed to `RunnerExitStatus` to better reflect the purpose of this enum.

Additionally, `Default` exit status should be renamed to `Normal` or `Standard` (or other), since `Default` can be confusing considering rust's https://doc.rust-lang.org/std/default/trait.Default.html trait.

**Comment by itsfloki** [comment]
@cptartur I would love to take this up if no one is working on it.

**Comment by cptartur** [comment]
Sure, assigned you.
