### ISSUE TITLE
Inline `internal_collect_tests`

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#553]
The `internal_collect_tests` function https://github.com/foundry-rs/starknet-foundry/blob/621a1a5abb49fe41f459f655901cff0c915809e8/crates/forge/src/lib.rs#L123C16-L123C16 is just one iterator and call to an another function, which doesn't really increase the readability of the code. 

It should be inlined to https://github.com/foundry-rs/starknet-foundry/blob/621a1a5abb49fe41f459f655901cff0c915809e8/crates/forge/src/lib.rs#L75

**Comment by enitrat** [comment]
up for that
