### ISSUE TITLE
Replace Protostar with Starknet Foundry in Starknet Book

### ISSUE THREAD

**Issue by Radinyn** [foundry-rs/starknet-foundry#556]
Currently Starknet Book still presents Protostar as a go-to tool for Starknet development providing a slightly misleading guide (it asks for the declaration of already declared HelloStarknet contract on testnet). We should make a PR and replace it with a new Starknet Foundry guide.

https://github.com/starknet-edu/starknetbook

**Comment by MaksymilianDemitraszek** [comment]
I talked with Omar, who is responsible for starknet book, if somebody is planning to work on this one, reach out to me. I will contact him to make sure this one is finalized quickly.
