### ISSUE TITLE
Bug reporting directly from CLI

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#563]
### Which component is your feature related to?

Forge, Cast

### Feature Request

In case forge or cast encounter a bug, show a link in console to open a bug report. Additionally, we could collect the stack trace and automatically include that in the report. 

Open question is where these issues should be collected - if we do it through GitHub it could result in a lot of duplicates and noise. Perhaps some intermediate platform from where issues would be manually created would be beneficial.

**Comment by Arcticae** [comment]
We have links to our support groups in the `--help`, should be sufficient.
