### ISSUE TITLE
Investigate scarb versions in `prepare_for_tests.sh`

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#566]
I think we might be setting incorrect scarb versions in `prepare_for_tests.sh`, causing problems when running the package tests. Additionally, we should not be using `asdf global` and something like `asdf shell` instead in the scripts, so we don't change the entire system configs of contributors.

**Comment by THenry14** [comment]
possible duplicate https://github.com/foundry-rs/starknet-foundry/issues/429
