### ISSUE TITLE
`simple_package_with_git_dependency` test fails for foreign contributions

### ISSUE THREAD

**Issue by Radinyn** [foundry-rs/starknet-foundry#568]
#567 

https://github.com/foundry-rs/starknet-foundry/actions/runs/6041546550/job/16412260069?pr=567

**Comment by Radinyn** [comment]
I've temporarily removed the requirement from `Forge E2E` tests, please restore it after fixing the bug.

**Comment by cptartur** [comment]
We are using `snforge_std = {{ git = "https://github.com/foundry-rs/starknet-foundry.git", branch = "{}" }}` in the `simple_package_with_git_dependency` test to fetch the dependency. 

For this to work with outside contributors, we should also fetch the user name and repo name in the CI and set it accordingly:  `{ git = "https://github.com/{}/{}", branch = "{}" }}`
