### ISSUE TITLE
Initial gas reporting

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#596]
Add support for displaying gas usage of the whole test.

**Comment by cptartur** [comment]
Blocked by #670

**Comment by MaksymilianDemitraszek** [comment]
We should report all of the resources not only the final gas calculation

**Comment by cptartur** [comment]
Blocked by #834

**Comment by MaksymilianDemitraszek** [comment]
It is not blocked anymore I assume
