### ISSUE TITLE
Add tests for the `conversions` crate

### ISSUE THREAD

**Issue by Radinyn** [foundry-rs/starknet-foundry#599]
- `assert x.to_y().to_x() == x`
- create new objects from `1`

**Comment by devnet0x** [comment]
GM...Would you be okay with something like this?

#[cfg(test)]
mod tests {
    use conversions::StarknetConversions;

    use starknet_api::{
        core::{ClassHash},
        hash::{StarkFelt},
    };

    #[test]
    fn test_class_hash_conversions() {
        let felt: StarkFelt = StarkFelt::new([1u8; 32]).unwrap();
        let class_hash = ClassHash(felt);

        assert_eq!(class_hash,class_hash.to_felt252().to_class_hash());
        assert_eq!(class_hash,class_hash.to_field_element().to_class_hash());
        assert_eq!(class_hash,class_hash.to_stark_felt().to_class_hash());
        assert_eq!(class_hash,class_hash.to_stark_hash().to_class_hash());
        assert_eq!(class_hash,class_hash.to_contract_address().to_class_hash());
        assert_eq!(class_hash,class_hash.to_short_string().to_class_hash());
        assert_eq!(class_hash,class_hash.to_nonce().to_class_hash());
    }
}

**Comment by devnet0x** [comment]
gm..may i be assigned to this issue?..thanks

**Comment by devnet0x** [comment]
src/stark_hash.rs conversion is missing, may i add it @cptartur ?

**Comment by Arcticae** [comment]
@devnet0x what you proposed above looks fine to me, although i would add more values to the test itself.

as for stark_hash.rs test - i think you can add it

**Comment by devnet0x** [comment]
I think its done...please could you check?...thanks
