### ISSUE TITLE
Implement multi-forking

### ISSUE THREAD

**Issue by war-in** [foundry-rs/starknet-foundry#600]
### Which component is your feature related to?

Forge

### Feature Request

There should be a way of forking a few different networks from different nodes. (see [forking database](https://github.com/foundry-rs/starknet-foundry/blob/master/design_documents/state_forking/state_forking.md#state-forking-architecture) section in the design doc).
Workers should be identified by their `rpc_url and block_id`.

**Comment by Arcticae** [comment]
FYI @war-in this should be postponed, after we get some feedback on initial release
