### ISSUE TITLE
Pefromance issues for satoru

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#602]
https://github.com/keep-starknet-strange/satoru/issues

Test execution takes more time than it should. Verify if the reason is execution or compilation.

**Comment by MaksymilianDemitraszek** [comment]
It might be because of high cost of repeated class hash calculation

**Comment by Arcticae** [comment]
We should consider caching the calculated class hash across the tests and see if it improves performance

**Comment by abulenok** [comment]
Most of the time is spent collecting tests https://github.com/foundry-rs/starknet-foundry/blob/e8b0c545d2a75cdfff83bc2e0a010220b3257cb4/crates/forge/src/lib.rs#L77  in particular in the `check` method https://github.com/foundry-rs/starknet-foundry/blob/e8b0c545d2a75cdfff83bc2e0a010220b3257cb4/crates/test-collector/src/lib.rs#L325-L327

This https://github.com/foundry-rs/starknet-foundry/issues/647 should improve the situation

**Comment by piotmag769** [comment]
https://github.com/foundry-rs/starknet-foundry/issues/624#issuecomment-1715784724

**Comment by Arcticae** [comment]
I think if this task resulted in some issues for performance being created, it can be closed @abulenok
