### ISSUE TITLE
Cheatcode for modifying `BlockInfo::sequencer_address`

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#609]
It can be mocked via spoof (not obligatory)

**Comment by abulenok** [comment]
@MaksymilianDemitraszek 

`TxInfo` and `BlockInfo` are both contained in `ExectutionInfo`, but these are separate entities.  The `spoof` cheatcode is for mocking `TxInfo`. I think it would be more natural not to mix `sequencer_address` mocking with `TxInfo` mocking. We can create a separate cheatcode for it or merge it with `roll` and `warp` into one cheatcode responsible for mocking different parts of `BlockInfo` (same approach as in `spoof`)

https://github.com/starkware-libs/cairo/blob/22d26d11d1165b5bed9c2ae58cf98947932c7e59/corelib/src/starknet/info.cairo

**Comment by MaksymilianDemitraszek** [comment]
True that @abulenok my bad, we should have a separate cheatcode for this, akin to `spoof` and `roll`
