### ISSUE TITLE
Cheatcodes should work in test state

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#612]
If we target address `0`, cheatcode should target test state

**Comment by MaksymilianDemitraszek** [comment]
This is urgent task, effectively blocking #611 .
We should implement it ForgeHintProcessor tries to execute hint, otherwise falls back to CheatnetSyscallHandler otherwise falls back to BlockifierSyscallHandler

**Comment by piotmag769** [comment]
Is it blocked by #670? @cptartur

**Comment by MaksymilianDemitraszek** [comment]
I don't think it is blocked but there may be merge conflicts

**Comment by MaksymilianDemitraszek** [comment]
Please make sure if event related cheatcodes work as well
