### ISSUE TITLE
Propagate error messages when using `unwrap`

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#614]
Raise by @enitrat https://t.me/starknet_foundry_support/518

**Comment by enitrat** [comment]
Adding some context as the title is not very descriptive - If a call made to a dispatcher fails, calling unwrap on it will make the test fail with `Result::unwrap failed`. This is not very informative and it would be better if the error raised in the entrypoint call was collected by the test runner.

**Comment by war-in** [comment]
Everything works fine while using a classic dispatcher. The above error was encountered when using `.unwrap()` on an error returned by the `SafeDispatcher` which should be handled explicitly.
