### ISSUE TITLE
Add test filter based on module name

### ISSUE THREAD

**Issue by enitrat** [foundry-rs/starknet-foundry#616]
### Which component is your feature related to?

Forge

### Feature Request

Currently the only way to filter tests is by either explicitly match `module_path::module_name` or just by name. 

It would be great to be able to run tests specifically from a specific package, e.g `snforge -f module_name`

**Comment by cptartur** [comment]
To make sure we are on the same page, support for Scarb workspaces won't resolve this issue? You'll be able to select specific Scarb packages to run test from once it added.

**Comment by enitrat** [comment]
sorry, I did a mistake, I meant module, not package 😬 

> snforge contract:: so it will only run test from contract.cairo module

sounds good!
