### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Bal7hazar** [foundry-rs/starknet-foundry#624]
### Which component is your bug related to?

Forge

### Foundry Version

0.5.0

### What operating system are you using?

Linux

### What system architecture are you using?

x86

### What happened

The memory usage is too high.

To reproduce, you can play `snforge`  on [satoru](https://github.com/keep-starknet-strange/satoru) and track memory usage of `snforge` process.

In my case it reaches 9.4 Go.

### Trace

The computer just freeze and I have to hard boot it.

Probably related to: https://github.com/software-mansion/scarb/issues/624

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

**Comment by piotmag769** [comment]
@Bal7hazar copying the message I sent on Satoru's telegram to not lose it:

"Hi guys, we (Starknet Foundry team) investigated the speed and memory issues when running snforge for Satoru.

Basically the temporary solution is to keep tests in the module tree of your package. Tried it on my laptop and those were the results:
- time: 441 s -> 150 s
- peak RAM usage: 9.4 GB -> around 1.5 GB

The main bottleneck for us is compilation and it is the best way to reduce its time for now (until compiler team does not introduce incremental compilation, but it is not their main focus atm)."

LMK if this solution helped!

**Comment by piotmag769** [comment]
Proposed improvement: #647

**Comment by piotmag769** [comment]
Closing the issue, if the solution did not help feel free to reopen!
