### ISSUE TITLE
Add info about manual installation on Windows in docs

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#629]
Rn we don't explicitly mention that the installation script won't work out of the box on windows, we should mention that manual installation is required. 
We can get inspiration from Scarb https://docs.swmansion.com/scarb/download.html#windows

**Comment by Etimfon007** [comment]
Is this still open for contributions?

**Comment by piotmag769** [comment]
@Etimfon007 yup, willing to work on that?

**Comment by piotmag769** [comment]
@Etimfon007 assigned you!

**Comment by cptartur** [comment]
Hey @Etimfon007, are you already in progress of creating the PR for this one? If not, let me temporarily un-assign you until #710 is done, so we're not blocking this issue for others.

**Comment by Etimfon007** [comment]
Hello @cptartur I'm on progress. Prolly before the end of this week I'll be merging a PR.

**Comment by Etimfon007** [comment]
Hello @cptartur can you temporarily un-assign me to this? I'm currently working on another issue. Just so that someone else can pick this one up to fast-track the development of StarkNet
