### ISSUE TITLE
Convert short string args to strings when it is possible

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#631]
```
spy
        .assert_emitted(
            @array![
                Event {
                    from: contract_address,
                    name: 'OrderCollateralDeltaAmountAutoUpdated',
                    keys: array![],
                    data: expected_data
                }
            ]
        );
```
fails because it does not fit into felt

**Comment by piotmag769** [comment]
Blocked by 2.3.0

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek events interface is being changed in #726 so the outlined case won't be an issue, can we close?

**Comment by MaksymilianDemitraszek** [comment]
@Arcticae I think it still influences for example values in declare

**Comment by piotmag769** [comment]
I think it is not actually 2.3.0 related, my bad on that

**Comment by MaksymilianDemitraszek** [comment]
I am unassigning cli, this is more core related. @piotmag769 why this has been moved to triage?

**Comment by piotmag769** [comment]
@MaksymilianDemitraszek I was mistaken that string support will be added in 2.3.0, so it's basically a task for a future

**Comment by Arcticae** [comment]
Duplicate
