### ISSUE TITLE
Add more resource estimation tests

### ISSUE THREAD

**Issue by Radinyn** [foundry-rs/starknet-foundry#635]
Can we add some more advanced cases, like with other builtins? 

_Originally posted by @Arcticae in https://github.com/foundry-rs/starknet-foundry/pull/605#discussion_r1321671899_

**Comment by piotmag769** [comment]
@Radinyn pls remember about label assigning 🙏

**Comment by Arcticae** [comment]
Closing since we got the tests we needed in other PR regarding gas
