### ISSUE TITLE
Calling a contract and then using `get_block_number` fails

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#659]
still fails if trying to use `get_block_number` and mock calls at same time:

<img width="1276" alt="Screenshot 2023-09-13 at 18 58 24" src="https://github.com/foundry-rs/starknet-foundry/assets/1091900/b644d770-bbd4-48e4-90c1-504e152c11fe">

_Originally posted by @delaaxe in https://github.com/foundry-rs/starknet-foundry/issues/645#issuecomment-1717906110_

**Comment by MaksymilianDemitraszek** [comment]
@cptartur PR with failing test https://github.com/foundry-rs/starknet-foundry/pull/680

**Comment by delaaxe** [comment]
PR tracking this problem: https://github.com/keep-starknet-strange/satoru/pull/383
