### ISSUE TITLE
Parallelise test execution 

### ISSUE THREAD

**Issue by abulenok** [foundry-rs/starknet-foundry#663]
### Which component is your feature related to?

Forge

### Feature Request

In the context of https://github.com/foundry-rs/starknet-foundry/issues/602 parallelisation as in https://github.com/foundry-rs/starknet-foundry/pull/662/files#diff-ea82c7cc5a4b99357fe5eef07f36c7e3188556251b522b3a3a227556d4196d98L270-R310 yields 2x speedup of Satoru's tests execution on my machine

Draft implementation https://github.com/foundry-rs/starknet-foundry/pull/662

**Comment by MaksymilianDemitraszek** [comment]
Some ideas https://github.com/foundry-rs/starknet-foundry/pull/608#discussion_r1325629476

For shared state we should investigate implementing parrallelism execution in batches. Example of shared state is exitfirst
