### ISSUE TITLE
Add `class_hash` caching 

### ISSUE THREAD

**Issue by abulenok** [foundry-rs/starknet-foundry#665]
### Which component is your feature related to?

Cheatnet

### Feature Request

[class hash computation](https://github.com/foundry-rs/starknet-foundry/blob/edd2e3562975ee3de69c0fe7b8af01414d2761c1/crates/cheatnet/src/cheatcodes/declare.rs#L61-L62) takes around 15% of the test execution time

Measured on Satoru test suite https://github.com/foundry-rs/starknet-foundry/issues/602

**Comment by piotmag769** [comment]
Is it still relevant? @Arcticae
