### ISSUE TITLE
Rename section name in docs

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#667]
![image](https://github.com/foundry-rs/starknet-foundry/assets/32527780/863dc8bb-a2c1-4008-82e4-a7463d9c1060)
Cast overview or Interactions with Starknet through cast. Name does not appear anywhere which may be confusing for people coming from foundry.

**Comment by cptartur** [comment]
I think we should name the section `Cast Overview` and rename the `Overview` subsection to something else.
