### ISSUE TITLE
Investigate if it's possible to fix diagnostic reports

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#668]
Currently all diagnostic reports from tests outside of the package e.g. from `tests` folder inform about non-existing lib.cairo file 

```console
error: Identifier not found.
 --> lib.cairo:45:21
 ```
 
Is is because we create a virtual package for each test case and the default entrypoint for each package is named `lib.cairo`. If anyone wants to take this task hit me up for detailed information.

**Comment by cptartur** [comment]
@piotmag769 please expand the descrition
