### ISSUE TITLE
Call `scarb build` and `scarb metadata` only once

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#671]
The new flow of `scarb build` should be:

Always call it before the for loop in `main_execution` in CURRENT WORKING DIRECTORY:
if run with `--workspace` arg: call `scarb build --workspace`
if run with `--package pkg` arg: call `scarb build --package pkg`
otherwise call `scarb build`

We should always call `scarb metadata` in CURRENT WORKING DIRECTORY

Blocked by `scarb-ui` - there is currently no way to get info about flags from `PackageFilter` directly (without workarounds like reading args manually or other not elegant stuff)

**Comment by maciektr** [comment]
I still do not see why you would be blocked by this. The target dir is still the same for every execution in the working directory. You should not rely on location of target dir apart from reding it from metadata. What exactly is impossible without knowing some target dir defaults before execution?
