### ISSUE TITLE
Export cheatcodes as scarb package

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#68]
https://github.com/software-mansion/protostar/issues/1997

Currently corelib is configured by setting a `CARGO_MANIFEST_DIR` environment variable. We should consider a better way of detecting the corelib.

Note: as of creation of this issue, corelib provided by scarb cannot be used. Protostar uses a modified corelib.

**Comment by piotmag769** [comment]
Blocked until Cairo 2.1.0 is released

**Comment by piotmag769** [comment]
https://github.com/foundry-rs/starknet-foundry/pull/212#discussion_r1269072821

**Comment by cptartur** [comment]
Can resolving #331 unblock this?

**Comment by piotmag769** [comment]
@cptartur it should
