### ISSUE TITLE
Add a test that verifies `class_hash`es are calculated correctly

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#689]
We only verify that `class_hash` is not 0, but there is no test that actually compares the calculated value agains an expected, precalculated one. This way we can have values for class hashes that are completely inconsistent with starknet but not be aware of it at all.

**Comment by Arcticae** [comment]
@cptartur why is this important to check from the perspective of the user?

**Comment by cptartur** [comment]
Mostly just to enforce consistency with the actual network
