### ISSUE TITLE
Monitoring "Added diagnostics for attributes not declared in plugins"

### ISSUE THREAD

**Issue by tkumor3** [foundry-rs/starknet-foundry#700]
Ensure that after release cairo 2.3.0, our diagnostic for forks works correctly.

related with: https://github.com/starkware-libs/cairo/pull/4096/files

**Comment by piotmag769** [comment]
Looking at https://github.com/software-mansion/scarb/pull/886 I don't think it is relevant anymore? They work just fine I guess

**Comment by piotmag769** [comment]
@tkumor3 @cptartur

**Comment by cptartur** [comment]
Doesn't seem relevant anymore.
