### ISSUE TITLE
Support advanced assumptions in fuzzer

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#708]
Right now it is possible to configure minimum and maximum generated value in fuzzer. We should support some way of configuring more complex assumptions about the output generated by the fuzzer. I.e. there should be some code way of configuring things like `all values used in fuzzer are greater than 10 and divisible by three` etc.

**Comment by cptartur** [comment]
First, let's create a design document for that.

**Comment by Arcticae** [comment]
Closing in favor of #2108
