### ISSUE TITLE
Raise gentle error when user tries to use syscalls not supported by `forge` test runner

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#71]
https://github.com/software-mansion/protostar/issues/1886

Currently we directly use cairo repo test runner. We do not want to include starknet state and other starknet features into our test runner, thus we should remove them

**Comment by piotmag769** [comment]
Is this still relevant? @MaksymilianDemitraszek @cptartur

**Comment by cptartur** [comment]
Not sure

**Comment by cptartur** [comment]
If user tries to use starknet related syscall in tests, we should throw user friendly error
