### ISSUE TITLE
Use capital letters consistently for every header in docs

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#710]
Currently we have:
"Writing your first test"
but also
"The Test Contract"

**Comment by Oyinbayode** [comment]
Hello @cptartur 

I'd love to work on this issue.

Is it available to work on?

I anticipate your response

**Comment by cptartur** [comment]
Sure! Assigning you to this one.

**Comment by cptartur** [comment]
Hey, @Oyinbayode pinging to check up on the issue status: Are you still planning to work on this one? Thanks!

**Comment by piotmag769** [comment]
@Oyinbayode unassigning you to not block this issue for others, will assign you if you open a PR

**Comment by Etimfon007** [comment]
@piotmag769 is this issue free?
I'll love to work on it.

**Comment by cptartur** [comment]
> @piotmag769 is this issue free? I'll love to work on it.

Sure, assigning you.

**Comment by piotmag769** [comment]
@Etimfon007 are you still working on this one?

**Comment by Etimfon007** [comment]
Yep. I'll submit a PR at the end of the week! 🙂
