### ISSUE TITLE
Test `#[ignore]` atrribute support

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#715]
We probasbly should upstream it to the compiler if it is not already there

**Comment by piotmag769** [comment]
Do we actually want to upstream that? I think we can just do 
```rust
if case.ignored {
    return TestCaseSummary::Ignored{ ... }
}
``` 
in`run_from_test_case`. I think it is more of a Forge task tbh, the only change that touches Cheatnet is that one line I mentioned above
