### ISSUE TITLE
Do not reimport functions from modules in `snforge_std` `lib.cairo`

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#718]
Functions from modules like `io` (`fs` #716) should not be reimported in the `lib.cairo` file, so we enforce rust-like importing of these e.g.

```cairo
use snforge_std::io;

// ...
io::read_txt(...);
```

or 

```cairo
use snforge_std::io::read_txt;
```

Instead of current

```cairo
use snforge_std::read_txt;
```

To resolve this, just remove unnecessary `use` clauses from the `lib.cairo` file (e.g. remove `use io::file_operations::read_json;`, leaving just `mod io` definition).

**Comment by Utilitycoder** [comment]
I will take care of this.

**Comment by piotmag769** [comment]
@Utilitycoder can be done together with #716 if you want to
Remember to update the imports in docs as well!

**Comment by Utilitycoder** [comment]
@piotmag769 cool, I will do that.

**Comment by Utilitycoder** [comment]
I am still trying to get myself familiar with the entire codebase again. Can you point me to the file path that these changes affect?

**Comment by piotmag769** [comment]
@Utilitycoder `lib.cairo` in this folder https://github.com/foundry-rs/starknet-foundry/tree/master/snforge_std/src
