### ISSUE TITLE
Investigate if adding context to `Failed setting up runner` is needed

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#735]
Before 2.3.0-rc0 reason Cairo -> Sierra compilation works when using double quotes, but Sierra -> CASM fails.

We should see if it still happens after bumping to 2.3.0-rc0. If it is, we should extend the error message with general info about double quotes being the possible reason

**Comment by cptartur** [comment]
Seems that 2.3.0 has an other bug related to that: If you forge to close quotes (either `'` or `"`), the compilation will not fail with an error but will not produce any artifacts. So in case of contracts, scarb will not produce any artifacts, and in terms of tests, the test will be silently ignored - it won't be compiled or collected.

**Comment by cptartur** [comment]
It now fails with a proper diagnostic message
