### ISSUE TITLE
Use code coverage tool in forge

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#747]

**Comment by MaksymilianDemitraszek** [comment]
From #277

**Comment by cptartur** [comment]
Intellij has a build in coverage that works well. Do you want to use coverage as part of the github checks? Otherwise I don't think we need to do anything.

**Comment by MaksymilianDemitraszek** [comment]
I think you wanted to do this ~2/3 months ago, if you don't think it is necessary feel free to close

**Comment by cptartur** [comment]
Yes I did but I'm not sure if we decided if we want to have it as part of the CI. If yes, let's keep this issue, otherwise we can close it because it's easy to setup locally.
