### ISSUE TITLE
Return correct block info while forking

### ISSUE THREAD

**Issue by war-in** [foundry-rs/starknet-foundry#748]
### Which component is your bug related to?

Forge

### Foundry Version

0.7.1

### What operating system are you using?

MacOS

### What system architecture are you using?

arm

### What happened

When a state is forked in a test, `get_block_timestamp` returns 0 even if block_id is set to the `Latest`.
We should improve `get_cheated_exec_info_ptr` in the `execution_info.rs` to use block info from the fork

### Is there an existing issue for this?

- [x] I have searched the existing issues and verified no issue exits for this problem.

**Comment by cptartur** [comment]
Shouldn't this issue only be linked to Cheatnet?
