### ISSUE TITLE
Investigate latest block caching

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#756]
It is hard to use right now because of performance

We could implement something like `Recent` block, which takes a block recent enough (perhaps invalidation time could be configurable) for the test to be valid.

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek is there a takeaway from our last discussion? I believe we should not do that

**Comment by MaksymilianDemitraszek** [comment]
If somebody would like to use latest block in their test it will have terrible performance. Using latest block is useful when you would like to make sure your contracts will work with the newest network state

**Comment by Arcticae** [comment]
Did you mean incremental state caching here? We really don't have any certainty that the state was not changed at requested address, so all state requests will have to be made for a block anyway.

**Comment by MaksymilianDemitraszek** [comment]
Agreed it could be problematic but we could maybe employ some optimistic strategies? Let's leave it in triage for now as a future idea

**Comment by piotmag769** [comment]
Isn't it done already? We use the block number instead of the tag so it will be cached
https://github.com/foundry-rs/starknet-foundry/blob/802dc2330c2e16573b98ba2c5b8139199d18fff8/crates/forge-runner/src/running.rs#L324

**Comment by war-in** [comment]
I'm not sure if @MaksymilianDemitraszek meant caching (at least not the one we have now) 🤔 From the discussion above I assume it could be resolved by some `incremental state caching` approach
