### ISSUE TITLE
Make `max_steps` customisable via `#[max_steps(X)]` attribute

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#779]
Currently it is set to 1M in [`build_block_context`](https://github.com/foundry-rs/starknet-foundry/blob/ee9180b5ea3988aa2776dec0448b351158f67887/crates/cheatnet/src/constants.rs#L101C18-L101C18). We should also change the default value to 3M to be consistent with starknet. https://docs.starknet.io/documentation/tools/limits_and_triggers/

https://t.me/starknet_foundry_support/725

**Comment by rkdud007** [comment]
i can try this one :)

**Comment by war-in** [comment]
Actually, I'm currently working on this, but you can take any other unassigned issue :)

**Comment by war-in** [comment]
Here is the branch. Feel free to checkout from it

https://github.com/foundry-rs/starknet-foundry/tree/war-in/779-max-steps

**Comment by Arcticae** [comment]
Blocked by 2.3.0

**Comment by piotmag769** [comment]
It is not really 2.3.0 related, removing the milestone. Btw isn't it a cli issue too? The main part of it is changing test collector
