### ISSUE TITLE
Docs Forge - Library Function: precalculate_address typo

### ISSUE THREAD

**Issue by robertkodra** [foundry-rs/starknet-foundry#796]
In the code example for [precalculate_address](https://foundry-rs.github.io/starknet-foundry/appendix/forge-library/precalculate_address.html), the `unwrap()` needs to be removed since the `precalculate_address` function returns as `ContractAddress`. 

```rust
    let contract_address = contract.precalculate_address(@constructor_calldata).unwrap();
```
Feel free to assign me.

**Comment by piotmag769** [comment]
@robertkodra thanks! Assigning you

**Comment by piotmag769** [comment]
Hi! Unassigned you to not block this issue for others, if you open a PR I will assign you again
