### ISSUE TITLE
Logging utility in deployment scripts

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#825]
We should come up with a helpers for logging in deployment scripts, to make debugging and tracing script execution easier for users. Logs could be directed to stdout/err or to a file depending on a flag.

We should also make sure error handling is designed as described in the design doc. This issue can be split into smaller ones if needed.

Consult cairo deployment scripts [design doc](https://github.com/foundry-rs/starknet-foundry/blob/master/design_documents/cairo_deployment_scripts.md) for more context.

**Comment by abulenok** [comment]
Created a separate issue for Result handling https://github.com/foundry-rs/starknet-foundry/issues/1361

**Comment by abulenok** [comment]
After internal discussion, we decided to close deployment script logging PRs, as the user can use newly added print! and println! Cairo macros for logging necessary information
