### ISSUE TITLE
Support calculating gas cost of whole test execution

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#834]
When running tests, we should be able to calculate its combined gas cost, that is: cost of all code in the test itself, probably extracted from the VM using https://github.com/starkware-libs/cairo/pull/4084 + the cost of blockifier calls which we are already calculating.

We should create some interface that makes the combined cost of the test available in the `run_from_test_case` https://github.com/foundry-rs/starknet-foundry/blob/894fedb266d30bfd633ae02a5d4c51d2119f846e/crates/forge/src/running.rs#L72 function, so it can be then collected and displayed by forge.

Additionally:
- [ ] Address the TODO in code

**Comment by cptartur** [comment]
This is blocked by blockifier getting bumped to 2.3.0-rc0 or higher.

**Comment by Arcticae** [comment]
Please do create a follow-up to parse the result and display it (for `forge-cli` team)
