### ISSUE TITLE
Split forge crate

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#839]
`forge` crate encapsulates to many responsibilities

We should split it into `cli` and `test-runner`

**Comment by cptartur** [comment]
I think we should just split `lib.cairo` into smaller modules. I don't see any benefit of making it entriely separate crates.

**Comment by MaksymilianDemitraszek** [comment]
Disagreed, It is better to keep responsibilities of crates small

**Comment by cptartur** [comment]
I just don't see how this split would go exactly. The CLI part is mostly just resolving things from scarb which is a separate module already, or just some code in `main.rs`. Also, the running code is also printing outputs so there's no clear separation between these.

This split can be done, but in my opinion it would require significant refactor (#175 should probably be done after all).

**Comment by MaksymilianDemitraszek** [comment]
I think this loop (and everything below it) should go into test runnet package 
https://github.com/foundry-rs/starknet-foundry/blob/1b897056179545d37f7b9f8b13d665d952d31459/crates/forge/src/lib.rs#L290

There is no need for refactor, printing can be part of the test running as well, cli responsibility should be define user interface, fetch args from different soruces and consolidate them.

**Comment by MaksymilianDemitraszek** [comment]
test collector is also thin, I don't see it as an major issue. I am not sure what would be the benefits of printing refactor if there are some but I don't also understand the goal you think about clearly.

**Comment by MaksymilianDemitraszek** [comment]
I see, not sure if we have any benefits of such control right now, would be useful if we consider implementing machine readable output. One way or another I don't see it blocking or conflicing suggested crate split in any what. those are separate concerns
