### ISSUE TITLE
Profiler

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#854]
Support profiling gas and steps usage per function. Details of this feature will be investigated after related blockers are resolved.

**Comment by cptartur** [comment]
Blocked by #846

**Comment by MaksymilianDemitraszek** [comment]
Should be implemented first #1239

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek what is the purpose of this issue?

**Comment by MaksymilianDemitraszek** [comment]
@Arcticae I have no idea tbh, closing
