### ISSUE TITLE
Automate release procedure

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#859]
We should add as script to the repository which would:
- Bump the versions (minor/patch as options perhaps?) in Cargo.toml
- Mark unreleased changelog sections with the version + date, add a new "template" for next release
- Create a tag with the new version
- Commit the changes
- Push the tag to the repo
- Emit a message that a release has been started. 

Display at the end (if possible):
- a link to release action
- a link to the draft release the changelog in the console with the instructions to copy it into the release notes on GH

Bonus idea:
If the release action could create a draft release with the input already pre-filled with the contents of latest changelog, this would be even better

**Comment by cptartur** [comment]
This could just be a workflow triggered by updating version in `Cargo.toml` as well.

**Comment by cptartur** [comment]
If we go with triggering the release workflow by merging a commit bumping package version in `Cargo.toml`, we must also support the following: It should be possible to prevent automatic flow from triggering (I propose by adding a specific keywords to commit name like `[NO RELEASE]`. 

It should be possible to manually prepare an release contents and create a tag, which will then trigger automated release flow.

Motivation for that is sometimes we want to publish a hotfix release with some changes cherrypicked from master. With fully automatic flow, it would not be possible in cases where some additional commits except for the hotfix ones has been added to master.

**Comment by cptartur** [comment]
An MVP of this feature could have a very minimal handling of `[NO RELEASE]` where it will just prevent an automation from progressing without any additional handling.
