### ISSUE TITLE
Added `asdf-starknet-foundry` plugin

### ISSUE THREAD

**Issue by akhercha** [foundry-rs/starknet-foundry#863]
### Which component is your feature related to?

Other (Please describe below)

### Feature Request

Hey,

For convenience & tests I created quickly the `asdf-starknet-foundry` plugin here:
https://github.com/akhercha/asdf-starknet-foundry

Maybe it's better if you take it from here & create a repo so it's prefixed with `foundry-rs` rather than my username.

Let me know if I should add something to it though!

**Comment by piotmag769** [comment]
@akhercha many thanks! Forked it https://github.com/foundry-rs/asdf-starknet-foundry and gave you credit in the readme, we are really grateful 🙏

**Comment by piotmag769** [comment]
Can be closed when https://github.com/asdf-vm/asdf-plugins/pull/902/files is merged

**Comment by cptartur** [comment]
Merged https://github.com/asdf-vm/asdf-plugins/pull/912
