### ISSUE TITLE
Add `verify` command to the cast tool

### ISSUE THREAD

**Issue by rjnrohit** [foundry-rs/starknet-foundry#892]
### Which component is your feature related to?

Cast

### Which component is your feature related to?

Cast

### Feature Request

Proposed design : https://github.com/foundry-rs/starknet-foundry/blob/master/design_documents/contract_verification.md

**Comment by THenry14** [comment]
Hi @rjnrohit !
Hope everything's going well! Just wanted to touch base regarding this issue. If you need any input, run into questions, or would like to discuss anything, feel free to reach out. We're here to support you if you run on any blockers :) cheers!

**Comment by rjnrohit** [comment]
Yea, we are waiting for the Voayger verification APIs to be stabilised. No any major blockers at this moment, we're just waiting from the voayger's team to publish the APIs. then I'll add some test to #875 , then we're gtg

**Comment by THenry14** [comment]
Perfect, thanks :)

**Comment by rjnrohit** [comment]
Still waiting from the voyager side to implement the verification APIs
