### ISSUE TITLE
Split `main_execution` function

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#906]

**Comment by piotmag769** [comment]
I don't think it is relevant anymore after #802.
@cptartur can you look at the `main.rs` and check if it looks fine for you?

**Comment by cptartur** [comment]
> I don't think it is relevant anymore after #802. @cptartur can you look at the `main.rs` and check if it looks fine for you?

Let's discuss it at the next sync

**Comment by cptartur** [comment]
Let's see what changes to main #41 introduces
