### ISSUE TITLE
Split test compilation target candidate (one without lib) and test compilation target

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#918]
I would consider spliting test compilation target candidate (one without lib) and test compilation target instead of keeping it as a single type, imo this is a reason behind your problems in describing this contract, how `lib.cairo` is ensured is an implementation detail so there could be alternative strategies.  

_Originally posted by @MaksymilianDemitraszek in https://github.com/foundry-rs/starknet-foundry/pull/780#pullrequestreview-1685488226_

**Comment by cptartur** [comment]
#971

**Comment by MaksymilianDemitraszek** [comment]
@cptartur why this has been closed?

**Comment by cptartur** [comment]
> @cptartur why this has been closed?

With changes introduced in #971, it doesn't make sense to split it. Generated `lib.cairo` is injected to the test collector directly

**Comment by MaksymilianDemitraszek** [comment]
@cptartur If you cancel the task pl
