### ISSUE TITLE
Use `CallContractResult` in `SyscallResponseWrapper` in `test_execution_syscall_handler`

### ISSUE THREAD

**Issue by war-in** [foundry-rs/starknet-foundry#927]
We should decide if we should change `CallContractResult` to be suitable for `SyscallResponseWrapper`

https://github.com/foundry-rs/starknet-foundry/pull/891/files/15d78564500aa8b99d39a37b043a6dcc66770267#r1360584549

**Comment by Arcticae** [comment]
We decided that it's not worth doing and maintaining our own transactions is a better choice here
