### ISSUE TITLE
Rename `projects` section in docs

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#932]
It is basically a section about configuration, we should maybe remove it and put it in `Getting started`?
It is also incomplete on Forge's side

**Comment by ATREAY** [comment]
Hey @piotmag769, can I work on this issue if you're not already working on it?

**Comment by piotmag769** [comment]
@ATREAY Sure, assigning you!

**Comment by ATREAY** [comment]
Hey @piotmag769, I noticed in the issue description that you mentioned the Forge section on the project config page isn't complete. Would you kindly provide a reference or source from where I can find more details to fix it?

**Comment by piotmag769** [comment]
@ATREAY I was thinking about fork configuration in Scarb.toml, I think we could include it in an example and link the page about fork configuration so we don't repeat the same thing two times
https://foundry-rs.github.io/starknet-foundry/testing/fork-testing.html#configure-fork-in-the-scarbtoml

**Comment by ATREAY** [comment]
Hey @piotmag769, I've included the necessary updates. Please take a look whenever you have time, and tell me if any changes are needed.
