### ISSUE TITLE
First steps section

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#933]
First steps section contains a paragraph:
```
Ensures that casm codegen is enabled in the Scarb.toml file.

# ...
[[target.starknet-contract]]
casm = true
# ...
```

Ensures -> Ensure

But, why we do need it at all? 🤔 Imo it brings unecessary clutter to the first steps section.

Maybe should be moved to : "using-snforge-with-existing-scarb-projects"

**Comment by cptartur** [comment]
#993
