### ISSUE TITLE
Add optional `--yes` flag to subcommands that require user input

### ISSUE THREAD

**Issue by THenry14** [foundry-rs/starknet-foundry#935]
We should add an optional `--yes` flag to `sncast account delete` (and other subcommands that require user input) to make them usable in non-interactive scenarios.

**Comment by kasteph** [comment]
Hi! Can I pick this up?

**Comment by THenry14** [comment]
Hi @kasteph !
Hope everything's going well! Just wanted to touch base regarding this issue. If you need any input, run into questions, or would like to discuss anything, feel free to reach out. We're here to support you if you run on any blockers :) cheers!

**Comment by kasteph** [comment]
Hi @THenry14! Will find the time this week to work on this.

**Comment by kasteph** [comment]
Hi @THenry14 I started with a draft at #1130 and wanted to know first whether I'm going in the right direction. Thank you!

**Comment by THenry14** [comment]
Hi @kasteph ! Thanks for reaching out. Yes, this is what I had in mind regarding this issue ;)

**Comment by THenry14** [comment]
Hi @kasteph , seems this issue has gone stale a bit, so will unassign you for now in order to free it up for other potential contributors. If you ever get some time and want to work on this (or any other free issue) feel free to reach out. thanks!
