### ISSUE TITLE
Fix output of `snforge init`

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#959]
In case `snforge init` fails, we output `Failed to initial new project`. This output should be `Failed to initialize new project` or preferably print some more descriptive message.

**Comment by ATREAY** [comment]
Hey @cptartur, can I work on this issue if you're not already working on it?

**Comment by cptartur** [comment]
Sure, let me know once you're done with #932 and I will assign you this one.

**Comment by cptartur** [comment]
Hey @ATREAY, since we are merging #932, are you still interested in this one?

**Comment by ATREAY** [comment]
Yes @cptartur, I'm still interested in working on this issue.

**Comment by cptartur** [comment]
Great, assigning!

**Comment by ATREAY** [comment]
Hey @cptartur, I have made the required changes. Would you kindly review them when you have a moment?
