### ISSUE TITLE
Consider maintaining the template repository

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#965]
Now that we have the github action we could maintain the template repository to make it easier to create new repositories using `snforge`. We can setup a CI with our github action there so it is available out of the box.

To make sure it is working with the latest version of snforge we can just use the latest version  of our tool in the CI. Maybe consider using it as a submodule for our `init` command?

https://github.com/foundry-rs/starknet_forge_template

**Comment by cptartur** [comment]
We should have a github action with `schedule` trigger (or similar) that re-runs checks so we know when package becomes outdated.

**Comment by cptartur** [comment]
We should also link this template in README.md

**Comment by cptartur** [comment]
Related #1039
