### ISSUE TITLE
Consolidate `Print` trait implementation in tests & contracts

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#986]
User should not have to import a separate thing just to print in the tests

**Comment by piotmag769** [comment]
> User should not have to import a separate thing just to print in the tests

Do they have to? They still import `snforge_std::PrintTrait`

**Comment by Arcticae** [comment]
@piotmag769 
`use snforge_std::PrintTrait;` for tests
`use debug::PrintTrait;` for contracts

i believe we should be able to do it with `debug::PrintTrait` so that it's consistent with standard methods

**Comment by Arcticae** [comment]
⬆  That's actually not true, but nonetheless preferable version would be where you use the `debug::PrintTrait`

Still i would put it on hold since i think with new strings there are some logging utilities coming in cairo if i'm not mistaken

**Comment by cptartur** [comment]
Once we move to a single print trait, we should make sure it works for various type, e.g. `ClassHash.
