### ISSUE TITLE
Consider adding `Sn` prefix to project names in all places

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#998]
Follow-up of #958 

Our project binaries use `sn` prefixes in all places, but usages of names with and without prefixes in other places are inconsistent. 

E.g. https://github.com/foundry-rs/starknet-foundry/blob/e0bdc7ce715bb2112380c7be8ddc6503e45ee494/crates/cast/src/main.rs#L21
or in docs headings

We should consider if we want to use consistent names in all places.

**Comment by cptartur** [comment]
cc @THenry14 @MaksymilianDemitraszek

**Comment by MaksymilianDemitraszek** [comment]
Can we create a separate task for chain interactions team?

**Comment by THenry14** [comment]
> Can we create a separate task for chain interactions team?

https://github.com/foundry-rs/starknet-foundry/issues/1001

**Comment by MaksymilianDemitraszek** [comment]
@Arcticae  I don't think so 😄  ![Screenshot 2023-12-19 at 11 57 35](https://github.com/foundry-rs/starknet-foundry/assets/32527780/cd2a5bf0-866d-45b1-a9ab-c1f96c8f5b8c)

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek linked the wrong task 😬

**Comment by piotmag769** [comment]
Is it done? Packages are not renamed 🤔
